{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE NegativeLiterals #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
{-# OPTIONS_GHC -fno-warn-missing-export-lists #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-- | Generated by Haskell protocol buffer compiler. DO NOT EDIT!
module Effects.Events where

import Control.Applicative ((<$>), (<*>), (<|>))
import Control.Applicative qualified as Hs
import Control.DeepSeq qualified as Hs
import Control.Monad qualified as Hs
import Data.ByteString qualified as Hs
import Data.Coerce qualified as Hs
import Data.Int qualified as Hs (Int16, Int32, Int64)
import Data.List.NonEmpty qualified as Hs (NonEmpty (..))
import Data.Map qualified as Hs (Map, mapKeysMonotonic)
import Data.Proxy qualified as Proxy
import Data.String qualified as Hs (fromString)
import Data.Text.Lazy qualified as Hs (Text)
import Data.Vector qualified as Hs (Vector)
import Data.Word qualified as Hs (Word16, Word32, Word64)
import GHC.Enum qualified as Hs
import GHC.Generics qualified as Hs
import Google.Protobuf.Wrappers.Polymorphic qualified as HsProtobuf
  ( Wrapped (..),
  )
import Proto3.Suite.Class qualified as HsProtobuf
import Proto3.Suite.DotProto qualified as HsProtobufAST
import Proto3.Suite.JSONPB ((.:), (.=))
import Proto3.Suite.JSONPB qualified as HsJSONPB
import Proto3.Suite.Types qualified as HsProtobuf
import Proto3.Wire qualified as HsProtobuf
import Proto3.Wire.Decode qualified as HsProtobuf
  ( Parser,
    RawField,
  )
import Unsafe.Coerce qualified as Hs
import Prelude qualified as Hs

data WaitForEventRequest
  = WaitForEventRequest
  { waitForEventRequestTypes :: (Hs.Vector Hs.Text),
    waitForEventRequestTimeoutSecs :: Hs.Int32,
    waitForEventRequestAfterEventId :: Hs.Word64
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData WaitForEventRequest)

instance (HsProtobuf.Named WaitForEventRequest) where
  nameOf _ = Hs.fromString "WaitForEventRequest"

instance (HsProtobuf.HasDefault WaitForEventRequest)

instance (HsProtobuf.Message WaitForEventRequest) where
  encodeMessage
    _
    WaitForEventRequest
      { waitForEventRequestTypes,
        waitForEventRequestTimeoutSecs,
        waitForEventRequestAfterEventId
      } =
      Hs.mappend
        ( Hs.mappend
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 1)
                ( ( Hs.coerce
                      @(Hs.Vector Hs.Text)
                      @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
                  )
                    waitForEventRequestTypes
                )
            )
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 2)
                waitForEventRequestTimeoutSecs
            )
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 3)
            waitForEventRequestAfterEventId
        )
  decodeMessage _ =
    Hs.pure WaitForEventRequest
      <*> ( ( HsProtobuf.coerceOver
                @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
                @(Hs.Vector Hs.Text)
            )
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 2)
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 3)
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Repeated HsProtobufAST.String)
        (HsProtobufAST.Single "types")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.Int32)
        (HsProtobufAST.Single "timeout_secs")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 3)
        (HsProtobufAST.Prim HsProtobufAST.UInt64)
        (HsProtobufAST.Single "after_event_id")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB WaitForEventRequest) where
  toJSONPB (WaitForEventRequest f1 f2 f3) =
    HsJSONPB.object
      [ "types"
          .= ( ( Hs.coerce
                   @(Hs.Vector Hs.Text)
                   @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
               )
                 f1
             ),
        "timeout_secs" .= f2,
        "after_event_id" .= f3
      ]
  toEncodingPB (WaitForEventRequest f1 f2 f3) =
    HsJSONPB.pairs
      [ "types"
          .= ( ( Hs.coerce
                   @(Hs.Vector Hs.Text)
                   @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
               )
                 f1
             ),
        "timeout_secs" .= f2,
        "after_event_id" .= f3
      ]

instance (HsJSONPB.FromJSONPB WaitForEventRequest) where
  parseJSONPB =
    HsJSONPB.withObject
      "WaitForEventRequest"
      ( \obj ->
          Hs.pure WaitForEventRequest
            <*> ( ( HsProtobuf.coerceOver
                      @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
                      @(Hs.Vector Hs.Text)
                  )
                    (obj .: "types")
                )
            <*> obj .: "timeout_secs"
            <*> obj .: "after_event_id"
      )

instance (HsJSONPB.ToJSON WaitForEventRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON WaitForEventRequest) where
  parseJSON = HsJSONPB.parseJSONPB

newtype WaitForEventResponse
  = WaitForEventResponse {waitForEventResponseEvent :: (Hs.Maybe Effects.Events.Event)}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData WaitForEventResponse)

instance (HsProtobuf.Named WaitForEventResponse) where
  nameOf _ = Hs.fromString "WaitForEventResponse"

instance (HsProtobuf.HasDefault WaitForEventResponse)

instance (HsProtobuf.Message WaitForEventResponse) where
  encodeMessage _ WaitForEventResponse {waitForEventResponseEvent} =
    ( HsProtobuf.encodeMessageField
        (HsProtobuf.FieldNumber 1)
        ( ( Hs.coerce
              @(Hs.Maybe Effects.Events.Event)
              @(HsProtobuf.Nested Effects.Events.Event)
          )
            waitForEventResponseEvent
        )
    )
  decodeMessage _ =
    Hs.pure WaitForEventResponse
      <*> ( ( HsProtobuf.coerceOver
                @(HsProtobuf.Nested Effects.Events.Event)
                @(Hs.Maybe Effects.Events.Event)
            )
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        ( HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "Event"))
        )
        (HsProtobufAST.Single "event")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB WaitForEventResponse) where
  toJSONPB (WaitForEventResponse f1) =
    HsJSONPB.object
      [ "event"
          .= ( ( Hs.coerce
                   @(Hs.Maybe Effects.Events.Event)
                   @(HsProtobuf.Nested Effects.Events.Event)
               )
                 f1
             )
      ]
  toEncodingPB (WaitForEventResponse f1) =
    HsJSONPB.pairs
      [ "event"
          .= ( ( Hs.coerce
                   @(Hs.Maybe Effects.Events.Event)
                   @(HsProtobuf.Nested Effects.Events.Event)
               )
                 f1
             )
      ]

instance (HsJSONPB.FromJSONPB WaitForEventResponse) where
  parseJSONPB =
    HsJSONPB.withObject
      "WaitForEventResponse"
      ( \obj ->
          Hs.pure WaitForEventResponse
            <*> ( ( HsProtobuf.coerceOver
                      @(HsProtobuf.Nested Effects.Events.Event)
                      @(Hs.Maybe Effects.Events.Event)
                  )
                    (obj .: "event")
                )
      )

instance (HsJSONPB.ToJSON WaitForEventResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON WaitForEventResponse) where
  parseJSON = HsJSONPB.parseJSONPB

data NotifyEventRequest
  = NotifyEventRequest
  { notifyEventRequestSessionId :: Hs.Text,
    notifyEventRequestEvent :: (Hs.Maybe Effects.Events.Event)
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData NotifyEventRequest)

instance (HsProtobuf.Named NotifyEventRequest) where
  nameOf _ = Hs.fromString "NotifyEventRequest"

instance (HsProtobuf.HasDefault NotifyEventRequest)

instance (HsProtobuf.Message NotifyEventRequest) where
  encodeMessage
    _
    NotifyEventRequest
      { notifyEventRequestSessionId,
        notifyEventRequestEvent
      } =
      Hs.mappend
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 1)
            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                notifyEventRequestSessionId
            )
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 2)
            ( ( Hs.coerce
                  @(Hs.Maybe Effects.Events.Event)
                  @(HsProtobuf.Nested Effects.Events.Event)
              )
                notifyEventRequestEvent
            )
        )
  decodeMessage _ =
    Hs.pure NotifyEventRequest
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
      <*> ( ( HsProtobuf.coerceOver
                @(HsProtobuf.Nested Effects.Events.Event)
                @(Hs.Maybe Effects.Events.Event)
            )
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "session_id")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        ( HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "Event"))
        )
        (HsProtobufAST.Single "event")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB NotifyEventRequest) where
  toJSONPB (NotifyEventRequest f1 f2) =
    HsJSONPB.object
      [ "session_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "event"
          .= ( ( Hs.coerce
                   @(Hs.Maybe Effects.Events.Event)
                   @(HsProtobuf.Nested Effects.Events.Event)
               )
                 f2
             )
      ]
  toEncodingPB (NotifyEventRequest f1 f2) =
    HsJSONPB.pairs
      [ "session_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "event"
          .= ( ( Hs.coerce
                   @(Hs.Maybe Effects.Events.Event)
                   @(HsProtobuf.Nested Effects.Events.Event)
               )
                 f2
             )
      ]

instance (HsJSONPB.FromJSONPB NotifyEventRequest) where
  parseJSONPB =
    HsJSONPB.withObject
      "NotifyEventRequest"
      ( \obj ->
          Hs.pure NotifyEventRequest
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "session_id")
                )
            <*> ( ( HsProtobuf.coerceOver
                      @(HsProtobuf.Nested Effects.Events.Event)
                      @(Hs.Maybe Effects.Events.Event)
                  )
                    (obj .: "event")
                )
      )

instance (HsJSONPB.ToJSON NotifyEventRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON NotifyEventRequest) where
  parseJSON = HsJSONPB.parseJSONPB

newtype NotifyEventResponse
  = NotifyEventResponse {notifyEventResponseSuccess :: Hs.Bool}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData NotifyEventResponse)

instance (HsProtobuf.Named NotifyEventResponse) where
  nameOf _ = Hs.fromString "NotifyEventResponse"

instance (HsProtobuf.HasDefault NotifyEventResponse)

instance (HsProtobuf.Message NotifyEventResponse) where
  encodeMessage _ NotifyEventResponse {notifyEventResponseSuccess} =
    ( HsProtobuf.encodeMessageField
        (HsProtobuf.FieldNumber 1)
        notifyEventResponseSuccess
    )
  decodeMessage _ =
    Hs.pure NotifyEventResponse
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 1)
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.Bool)
        (HsProtobufAST.Single "success")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB NotifyEventResponse) where
  toJSONPB (NotifyEventResponse f1) =
    HsJSONPB.object ["success" .= f1]
  toEncodingPB (NotifyEventResponse f1) =
    HsJSONPB.pairs ["success" .= f1]

instance (HsJSONPB.FromJSONPB NotifyEventResponse) where
  parseJSONPB =
    HsJSONPB.withObject
      "NotifyEventResponse"
      (\obj -> Hs.pure NotifyEventResponse <*> obj .: "success")

instance (HsJSONPB.ToJSON NotifyEventResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON NotifyEventResponse) where
  parseJSON = HsJSONPB.parseJSONPB

data Event
  = Event
  { eventEventId :: Hs.Word64,
    eventEventType :: (Hs.Maybe EventEventType)
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData Event)

instance (HsProtobuf.Named Event) where
  nameOf _ = Hs.fromString "Event"

instance (HsProtobuf.HasDefault Event)

instance (HsProtobuf.Message Event) where
  encodeMessage _ Event {eventEventId, eventEventType} =
    Hs.mappend
      ( HsProtobuf.encodeMessageField
          (HsProtobuf.FieldNumber 3)
          eventEventId
      )
      ( case eventEventType of
          Hs.Nothing -> Hs.mempty
          Hs.Just x ->
            case x of
              EventEventTypeAgentMessage y ->
                HsProtobuf.encodeMessageField
                  (HsProtobuf.FieldNumber 1)
                  ( ( Hs.coerce
                        @(Hs.Maybe Effects.Events.AgentMessage)
                        @(HsProtobuf.Nested Effects.Events.AgentMessage)
                    )
                      (Hs.Just y)
                  )
              EventEventTypeTimeout y ->
                HsProtobuf.encodeMessageField
                  (HsProtobuf.FieldNumber 2)
                  ( ( Hs.coerce
                        @(Hs.Maybe Effects.Events.Timeout)
                        @(HsProtobuf.Nested Effects.Events.Timeout)
                    )
                      (Hs.Just y)
                  )
              EventEventTypeIssueClosed y ->
                HsProtobuf.encodeMessageField
                  (HsProtobuf.FieldNumber 4)
                  ( ( Hs.coerce
                        @(Hs.Maybe Effects.Events.IssueClosed)
                        @(HsProtobuf.Nested Effects.Events.IssueClosed)
                    )
                      (Hs.Just y)
                  )
      )
  decodeMessage _ =
    Hs.pure Event
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 3)
      <*> HsProtobuf.oneof
        Hs.Nothing
        [ ( (HsProtobuf.FieldNumber 1),
            Hs.pure (Hs.fmap EventEventTypeAgentMessage)
              <*> ( ( HsProtobuf.coerceOver
                        @(HsProtobuf.Nested Effects.Events.AgentMessage)
                        @(Hs.Maybe Effects.Events.AgentMessage)
                    )
                      HsProtobuf.decodeMessageField
                  )
          ),
          ( (HsProtobuf.FieldNumber 2),
            Hs.pure (Hs.fmap EventEventTypeTimeout)
              <*> ( ( HsProtobuf.coerceOver
                        @(HsProtobuf.Nested Effects.Events.Timeout)
                        @(Hs.Maybe Effects.Events.Timeout)
                    )
                      HsProtobuf.decodeMessageField
                  )
          ),
          ( (HsProtobuf.FieldNumber 4),
            Hs.pure (Hs.fmap EventEventTypeIssueClosed)
              <*> ( ( HsProtobuf.coerceOver
                        @(HsProtobuf.Nested Effects.Events.IssueClosed)
                        @(Hs.Maybe Effects.Events.IssueClosed)
                    )
                      HsProtobuf.decodeMessageField
                  )
          )
        ]
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 3)
        (HsProtobufAST.Prim HsProtobufAST.UInt64)
        (HsProtobufAST.Single "event_id")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB Event) where
  toJSONPB (Event f3 f1_or_f2_or_f4) =
    HsJSONPB.object
      [ "event_id" .= f3,
        ( let encodeEvent_type =
                ( case f1_or_f2_or_f4 of
                    Hs.Just (EventEventTypeAgentMessage f1) ->
                      HsJSONPB.pair "agent_message" f1
                    Hs.Just (EventEventTypeTimeout f2) -> HsJSONPB.pair "timeout" f2
                    Hs.Just (EventEventTypeIssueClosed f4) ->
                      HsJSONPB.pair "issue_closed" f4
                    Hs.Nothing -> Hs.mempty
                )
           in ( \options ->
                  if HsJSONPB.optEmitNamedOneof options
                    then
                      ("event_type" .= HsJSONPB.objectOrNull [encodeEvent_type] options)
                        options
                    else
                      encodeEvent_type options
              )
        )
      ]
  toEncodingPB (Event f3 f1_or_f2_or_f4) =
    HsJSONPB.pairs
      [ "event_id" .= f3,
        ( let encodeEvent_type =
                ( case f1_or_f2_or_f4 of
                    Hs.Just (EventEventTypeAgentMessage f1) ->
                      HsJSONPB.pair "agent_message" f1
                    Hs.Just (EventEventTypeTimeout f2) -> HsJSONPB.pair "timeout" f2
                    Hs.Just (EventEventTypeIssueClosed f4) ->
                      HsJSONPB.pair "issue_closed" f4
                    Hs.Nothing -> Hs.mempty
                )
           in ( \options ->
                  if HsJSONPB.optEmitNamedOneof options
                    then
                      ("event_type" .= HsJSONPB.pairsOrNull [encodeEvent_type] options)
                        options
                    else
                      encodeEvent_type options
              )
        )
      ]

instance (HsJSONPB.FromJSONPB Event) where
  parseJSONPB =
    HsJSONPB.withObject
      "Event"
      ( \obj ->
          Hs.pure Event
            <*> obj .: "event_id"
            <*> ( let parseEvent_type parseObj =
                        Hs.msum
                          [ Hs.Just Hs.. EventEventTypeAgentMessage
                              <$> HsJSONPB.parseField parseObj "agent_message",
                            Hs.Just Hs.. EventEventTypeTimeout
                              <$> HsJSONPB.parseField parseObj "timeout",
                            Hs.Just Hs.. EventEventTypeIssueClosed
                              <$> HsJSONPB.parseField parseObj "issue_closed",
                            Hs.pure Hs.Nothing
                          ]
                   in ( obj .: "event_type"
                          Hs.>>= HsJSONPB.withObject "event_type" parseEvent_type
                      )
                        <|> (parseEvent_type obj)
                )
      )

instance (HsJSONPB.ToJSON Event) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON Event) where
  parseJSON = HsJSONPB.parseJSONPB

data EventEventType
  = EventEventTypeAgentMessage Effects.Events.AgentMessage
  | EventEventTypeTimeout Effects.Events.Timeout
  | EventEventTypeIssueClosed Effects.Events.IssueClosed
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData EventEventType)

instance (HsProtobuf.Named EventEventType) where
  nameOf _ = Hs.fromString "EventEventType"

data AgentMessage
  = AgentMessage
  { agentMessageAgentId :: Hs.Text,
    agentMessageStatus :: Hs.Text,
    agentMessageChanges :: (Hs.Vector Hs.Text),
    agentMessageMessage :: Hs.Text
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData AgentMessage)

instance (HsProtobuf.Named AgentMessage) where
  nameOf _ = Hs.fromString "AgentMessage"

instance (HsProtobuf.HasDefault AgentMessage)

instance (HsProtobuf.Message AgentMessage) where
  encodeMessage
    _
    AgentMessage
      { agentMessageAgentId,
        agentMessageStatus,
        agentMessageChanges,
        agentMessageMessage
      } =
      Hs.mappend
        ( Hs.mappend
            ( Hs.mappend
                ( HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 1)
                    ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                        agentMessageAgentId
                    )
                )
                ( HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 2)
                    ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                        agentMessageStatus
                    )
                )
            )
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 3)
                ( ( Hs.coerce
                      @(Hs.Vector Hs.Text)
                      @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
                  )
                    agentMessageChanges
                )
            )
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 4)
            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                agentMessageMessage
            )
        )
  decodeMessage _ =
    Hs.pure AgentMessage
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
      <*> ( ( HsProtobuf.coerceOver
                @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
                @(Hs.Vector Hs.Text)
            )
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 3)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 4)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "agent_id")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "status")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 3)
        (HsProtobufAST.Repeated HsProtobufAST.String)
        (HsProtobufAST.Single "changes")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 4)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "message")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB AgentMessage) where
  toJSONPB (AgentMessage f1 f2 f3 f4) =
    HsJSONPB.object
      [ "agent_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "status" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "changes"
          .= ( ( Hs.coerce
                   @(Hs.Vector Hs.Text)
                   @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
               )
                 f3
             ),
        "message"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4)
      ]
  toEncodingPB (AgentMessage f1 f2 f3 f4) =
    HsJSONPB.pairs
      [ "agent_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "status" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "changes"
          .= ( ( Hs.coerce
                   @(Hs.Vector Hs.Text)
                   @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
               )
                 f3
             ),
        "message"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4)
      ]

instance (HsJSONPB.FromJSONPB AgentMessage) where
  parseJSONPB =
    HsJSONPB.withObject
      "AgentMessage"
      ( \obj ->
          Hs.pure AgentMessage
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "agent_id")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "status")
                )
            <*> ( ( HsProtobuf.coerceOver
                      @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
                      @(Hs.Vector Hs.Text)
                  )
                    (obj .: "changes")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "message")
                )
      )

instance (HsJSONPB.ToJSON AgentMessage) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON AgentMessage) where
  parseJSON = HsJSONPB.parseJSONPB

newtype Timeout
  = Timeout {timeoutTimeoutSecs :: Hs.Int32}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData Timeout)

instance (HsProtobuf.Named Timeout) where
  nameOf _ = Hs.fromString "Timeout"

instance (HsProtobuf.HasDefault Timeout)

instance (HsProtobuf.Message Timeout) where
  encodeMessage _ Timeout {timeoutTimeoutSecs} =
    ( HsProtobuf.encodeMessageField
        (HsProtobuf.FieldNumber 1)
        timeoutTimeoutSecs
    )
  decodeMessage _ =
    Hs.pure Timeout
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 1)
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.Int32)
        (HsProtobufAST.Single "timeout_secs")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB Timeout) where
  toJSONPB (Timeout f1) = HsJSONPB.object ["timeout_secs" .= f1]
  toEncodingPB (Timeout f1) = HsJSONPB.pairs ["timeout_secs" .= f1]

instance (HsJSONPB.FromJSONPB Timeout) where
  parseJSONPB =
    HsJSONPB.withObject
      "Timeout"
      (\obj -> Hs.pure Timeout <*> obj .: "timeout_secs")

instance (HsJSONPB.ToJSON Timeout) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON Timeout) where
  parseJSON = HsJSONPB.parseJSONPB

data IssueClosed
  = IssueClosed
  { issueClosedIssueId :: Hs.Word64,
    issueClosedClosedBy :: Hs.Text
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData IssueClosed)

instance (HsProtobuf.Named IssueClosed) where
  nameOf _ = Hs.fromString "IssueClosed"

instance (HsProtobuf.HasDefault IssueClosed)

instance (HsProtobuf.Message IssueClosed) where
  encodeMessage
    _
    IssueClosed {issueClosedIssueId, issueClosedClosedBy} =
      Hs.mappend
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 1)
            issueClosedIssueId
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 2)
            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                issueClosedClosedBy
            )
        )
  decodeMessage _ =
    Hs.pure IssueClosed
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 1)
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.UInt64)
        (HsProtobufAST.Single "issue_id")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "closed_by")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB IssueClosed) where
  toJSONPB (IssueClosed f1 f2) =
    HsJSONPB.object
      [ "issue_id" .= f1,
        "closed_by"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)
      ]
  toEncodingPB (IssueClosed f1 f2) =
    HsJSONPB.pairs
      [ "issue_id" .= f1,
        "closed_by"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)
      ]

instance (HsJSONPB.FromJSONPB IssueClosed) where
  parseJSONPB =
    HsJSONPB.withObject
      "IssueClosed"
      ( \obj ->
          Hs.pure IssueClosed
            <*> obj .: "issue_id"
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "closed_by")
                )
      )

instance (HsJSONPB.ToJSON IssueClosed) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON IssueClosed) where
  parseJSON = HsJSONPB.parseJSONPB

newtype Address
  = Address {addressKind :: (Hs.Maybe AddressKind)}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData Address)

instance (HsProtobuf.Named Address) where
  nameOf _ = Hs.fromString "Address"

instance (HsProtobuf.HasDefault Address)

instance (HsProtobuf.Message Address) where
  encodeMessage _ Address {addressKind} =
    ( case addressKind of
        Hs.Nothing -> Hs.mempty
        Hs.Just x ->
          case x of
            AddressKindAgent y ->
              HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 1)
                ( HsProtobuf.ForceEmit
                    ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) y)
                )
            AddressKindTeam y ->
              HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 2)
                ( ( Hs.coerce
                      @(Hs.Maybe Effects.Events.TeamAddress)
                      @(HsProtobuf.Nested Effects.Events.TeamAddress)
                  )
                    (Hs.Just y)
                )
    )
  decodeMessage _ =
    Hs.pure Address
      <*> HsProtobuf.oneof
        Hs.Nothing
        [ ( (HsProtobuf.FieldNumber 1),
            Hs.pure (Hs.Just Hs.. AddressKindAgent)
              <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                      HsProtobuf.decodeMessageField
                  )
          ),
          ( (HsProtobuf.FieldNumber 2),
            Hs.pure (Hs.fmap AddressKindTeam)
              <*> ( ( HsProtobuf.coerceOver
                        @(HsProtobuf.Nested Effects.Events.TeamAddress)
                        @(Hs.Maybe Effects.Events.TeamAddress)
                    )
                      HsProtobuf.decodeMessageField
                  )
          )
        ]
  dotProto _ = []

instance (HsJSONPB.ToJSONPB Address) where
  toJSONPB (Address f1_or_f2) =
    HsJSONPB.object
      [ ( let encodeKind =
                ( case f1_or_f2 of
                    Hs.Just (AddressKindAgent f1) ->
                      HsJSONPB.pair
                        "agent"
                        ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)
                    Hs.Just (AddressKindTeam f2) -> HsJSONPB.pair "team" f2
                    Hs.Nothing -> Hs.mempty
                )
           in ( \options ->
                  if HsJSONPB.optEmitNamedOneof options
                    then
                      ("kind" .= HsJSONPB.objectOrNull [encodeKind] options) options
                    else
                      encodeKind options
              )
        )
      ]
  toEncodingPB (Address f1_or_f2) =
    HsJSONPB.pairs
      [ ( let encodeKind =
                ( case f1_or_f2 of
                    Hs.Just (AddressKindAgent f1) ->
                      HsJSONPB.pair
                        "agent"
                        ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)
                    Hs.Just (AddressKindTeam f2) -> HsJSONPB.pair "team" f2
                    Hs.Nothing -> Hs.mempty
                )
           in ( \options ->
                  if HsJSONPB.optEmitNamedOneof options
                    then
                      ("kind" .= HsJSONPB.pairsOrNull [encodeKind] options) options
                    else
                      encodeKind options
              )
        )
      ]

instance (HsJSONPB.FromJSONPB Address) where
  parseJSONPB =
    HsJSONPB.withObject
      "Address"
      ( \obj ->
          Hs.pure Address
            <*> ( let parseKind parseObj =
                        Hs.msum
                          [ Hs.Just
                              Hs.. AddressKindAgent
                              Hs.. (Hs.coerce @(HsProtobuf.String Hs.Text) @Hs.Text)
                              <$> HsJSONPB.parseField parseObj "agent",
                            Hs.Just Hs.. AddressKindTeam
                              <$> HsJSONPB.parseField parseObj "team",
                            Hs.pure Hs.Nothing
                          ]
                   in (obj .: "kind" Hs.>>= HsJSONPB.withObject "kind" parseKind)
                        <|> (parseKind obj)
                )
      )

instance (HsJSONPB.ToJSON Address) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON Address) where
  parseJSON = HsJSONPB.parseJSONPB

data AddressKind
  = AddressKindAgent Hs.Text
  | AddressKindTeam Effects.Events.TeamAddress
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData AddressKind)

instance (HsProtobuf.Named AddressKind) where
  nameOf _ = Hs.fromString "AddressKind"

data TeamAddress
  = TeamAddress
  { teamAddressTeam :: Hs.Text,
    teamAddressMember :: Hs.Text
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData TeamAddress)

instance (HsProtobuf.Named TeamAddress) where
  nameOf _ = Hs.fromString "TeamAddress"

instance (HsProtobuf.HasDefault TeamAddress)

instance (HsProtobuf.Message TeamAddress) where
  encodeMessage _ TeamAddress {teamAddressTeam, teamAddressMember} =
    Hs.mappend
      ( HsProtobuf.encodeMessageField
          (HsProtobuf.FieldNumber 1)
          ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              teamAddressTeam
          )
      )
      ( HsProtobuf.encodeMessageField
          (HsProtobuf.FieldNumber 2)
          ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              teamAddressMember
          )
      )
  decodeMessage _ =
    Hs.pure TeamAddress
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "team")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "member")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB TeamAddress) where
  toJSONPB (TeamAddress f1 f2) =
    HsJSONPB.object
      [ "team" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "member" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)
      ]
  toEncodingPB (TeamAddress f1 f2) =
    HsJSONPB.pairs
      [ "team" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "member" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)
      ]

instance (HsJSONPB.FromJSONPB TeamAddress) where
  parseJSONPB =
    HsJSONPB.withObject
      "TeamAddress"
      ( \obj ->
          Hs.pure TeamAddress
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "team")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "member")
                )
      )

instance (HsJSONPB.ToJSON TeamAddress) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON TeamAddress) where
  parseJSON = HsJSONPB.parseJSONPB

data SendMessageRequest
  = SendMessageRequest
  { sendMessageRequestRecipient :: (Hs.Maybe Effects.Events.Address),
    sendMessageRequestContent :: Hs.Text,
    sendMessageRequestSummary :: Hs.Text
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData SendMessageRequest)

instance (HsProtobuf.Named SendMessageRequest) where
  nameOf _ = Hs.fromString "SendMessageRequest"

instance (HsProtobuf.HasDefault SendMessageRequest)

instance (HsProtobuf.Message SendMessageRequest) where
  encodeMessage
    _
    SendMessageRequest
      { sendMessageRequestRecipient,
        sendMessageRequestContent,
        sendMessageRequestSummary
      } =
      Hs.mappend
        ( Hs.mappend
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 1)
                ( ( Hs.coerce
                      @(Hs.Maybe Effects.Events.Address)
                      @(HsProtobuf.Nested Effects.Events.Address)
                  )
                    sendMessageRequestRecipient
                )
            )
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 2)
                ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                    sendMessageRequestContent
                )
            )
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 3)
            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                sendMessageRequestSummary
            )
        )
  decodeMessage _ =
    Hs.pure SendMessageRequest
      <*> ( ( HsProtobuf.coerceOver
                @(HsProtobuf.Nested Effects.Events.Address)
                @(Hs.Maybe Effects.Events.Address)
            )
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 3)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        ( HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "Address"))
        )
        (HsProtobufAST.Single "recipient")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "content")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 3)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "summary")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB SendMessageRequest) where
  toJSONPB (SendMessageRequest f1 f2 f3) =
    HsJSONPB.object
      [ "recipient"
          .= ( ( Hs.coerce
                   @(Hs.Maybe Effects.Events.Address)
                   @(HsProtobuf.Nested Effects.Events.Address)
               )
                 f1
             ),
        "content"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "summary"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)
      ]
  toEncodingPB (SendMessageRequest f1 f2 f3) =
    HsJSONPB.pairs
      [ "recipient"
          .= ( ( Hs.coerce
                   @(Hs.Maybe Effects.Events.Address)
                   @(HsProtobuf.Nested Effects.Events.Address)
               )
                 f1
             ),
        "content"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "summary"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)
      ]

instance (HsJSONPB.FromJSONPB SendMessageRequest) where
  parseJSONPB =
    HsJSONPB.withObject
      "SendMessageRequest"
      ( \obj ->
          Hs.pure SendMessageRequest
            <*> ( ( HsProtobuf.coerceOver
                      @(HsProtobuf.Nested Effects.Events.Address)
                      @(Hs.Maybe Effects.Events.Address)
                  )
                    (obj .: "recipient")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "content")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "summary")
                )
      )

instance (HsJSONPB.ToJSON SendMessageRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON SendMessageRequest) where
  parseJSON = HsJSONPB.parseJSONPB

data SendMessageResponse
  = SendMessageResponse
  { sendMessageResponseSuccess :: Hs.Bool,
    sendMessageResponseDeliveryMethod :: Hs.Text
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData SendMessageResponse)

instance (HsProtobuf.Named SendMessageResponse) where
  nameOf _ = Hs.fromString "SendMessageResponse"

instance (HsProtobuf.HasDefault SendMessageResponse)

instance (HsProtobuf.Message SendMessageResponse) where
  encodeMessage
    _
    SendMessageResponse
      { sendMessageResponseSuccess,
        sendMessageResponseDeliveryMethod
      } =
      Hs.mappend
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 1)
            sendMessageResponseSuccess
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 2)
            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                sendMessageResponseDeliveryMethod
            )
        )
  decodeMessage _ =
    Hs.pure SendMessageResponse
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 1)
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.Bool)
        (HsProtobufAST.Single "success")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "delivery_method")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB SendMessageResponse) where
  toJSONPB (SendMessageResponse f1 f2) =
    HsJSONPB.object
      [ "success" .= f1,
        "delivery_method"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)
      ]
  toEncodingPB (SendMessageResponse f1 f2) =
    HsJSONPB.pairs
      [ "success" .= f1,
        "delivery_method"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)
      ]

instance (HsJSONPB.FromJSONPB SendMessageResponse) where
  parseJSONPB =
    HsJSONPB.withObject
      "SendMessageResponse"
      ( \obj ->
          Hs.pure SendMessageResponse
            <*> obj .: "success"
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "delivery_method")
                )
      )

instance (HsJSONPB.ToJSON SendMessageResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON SendMessageResponse) where
  parseJSON = HsJSONPB.parseJSONPB

data SendTmuxMessageRequest
  = SendTmuxMessageRequest
  { sendTmuxMessageRequestRecipient :: (Hs.Maybe Effects.Events.Address),
    sendTmuxMessageRequestContent :: Hs.Text,
    sendTmuxMessageRequestSummary :: Hs.Text
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData SendTmuxMessageRequest)

instance (HsProtobuf.Named SendTmuxMessageRequest) where
  nameOf _ = Hs.fromString "SendTmuxMessageRequest"

instance (HsProtobuf.HasDefault SendTmuxMessageRequest)

instance (HsProtobuf.Message SendTmuxMessageRequest) where
  encodeMessage
    _
    SendTmuxMessageRequest
      { sendTmuxMessageRequestRecipient,
        sendTmuxMessageRequestContent,
        sendTmuxMessageRequestSummary
      } =
      Hs.mappend
        ( Hs.mappend
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 1)
                ( ( Hs.coerce
                      @(Hs.Maybe Effects.Events.Address)
                      @(HsProtobuf.Nested Effects.Events.Address)
                  )
                    sendTmuxMessageRequestRecipient
                )
            )
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 2)
                ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                    sendTmuxMessageRequestContent
                )
            )
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 3)
            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                sendTmuxMessageRequestSummary
            )
        )
  decodeMessage _ =
    Hs.pure SendTmuxMessageRequest
      <*> ( ( HsProtobuf.coerceOver
                @(HsProtobuf.Nested Effects.Events.Address)
                @(Hs.Maybe Effects.Events.Address)
            )
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 3)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        ( HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "Address"))
        )
        (HsProtobufAST.Single "recipient")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "content")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 3)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "summary")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB SendTmuxMessageRequest) where
  toJSONPB (SendTmuxMessageRequest f1 f2 f3) =
    HsJSONPB.object
      [ "recipient"
          .= ( ( Hs.coerce
                   @(Hs.Maybe Effects.Events.Address)
                   @(HsProtobuf.Nested Effects.Events.Address)
               )
                 f1
             ),
        "content"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "summary"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)
      ]
  toEncodingPB (SendTmuxMessageRequest f1 f2 f3) =
    HsJSONPB.pairs
      [ "recipient"
          .= ( ( Hs.coerce
                   @(Hs.Maybe Effects.Events.Address)
                   @(HsProtobuf.Nested Effects.Events.Address)
               )
                 f1
             ),
        "content"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "summary"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)
      ]

instance (HsJSONPB.FromJSONPB SendTmuxMessageRequest) where
  parseJSONPB =
    HsJSONPB.withObject
      "SendTmuxMessageRequest"
      ( \obj ->
          Hs.pure SendTmuxMessageRequest
            <*> ( ( HsProtobuf.coerceOver
                      @(HsProtobuf.Nested Effects.Events.Address)
                      @(Hs.Maybe Effects.Events.Address)
                  )
                    (obj .: "recipient")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "content")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "summary")
                )
      )

instance (HsJSONPB.ToJSON SendTmuxMessageRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON SendTmuxMessageRequest) where
  parseJSON = HsJSONPB.parseJSONPB

data SendTmuxMessageResponse
  = SendTmuxMessageResponse
  { sendTmuxMessageResponseSuccess :: Hs.Bool,
    sendTmuxMessageResponseDeliveryMethod :: Hs.Text
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData SendTmuxMessageResponse)

instance (HsProtobuf.Named SendTmuxMessageResponse) where
  nameOf _ = Hs.fromString "SendTmuxMessageResponse"

instance (HsProtobuf.HasDefault SendTmuxMessageResponse)

instance (HsProtobuf.Message SendTmuxMessageResponse) where
  encodeMessage
    _
    SendTmuxMessageResponse
      { sendTmuxMessageResponseSuccess,
        sendTmuxMessageResponseDeliveryMethod
      } =
      Hs.mappend
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 1)
            sendTmuxMessageResponseSuccess
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 2)
            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                sendTmuxMessageResponseDeliveryMethod
            )
        )
  decodeMessage _ =
    Hs.pure SendTmuxMessageResponse
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 1)
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.Bool)
        (HsProtobufAST.Single "success")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "delivery_method")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB SendTmuxMessageResponse) where
  toJSONPB (SendTmuxMessageResponse f1 f2) =
    HsJSONPB.object
      [ "success" .= f1,
        "delivery_method"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)
      ]
  toEncodingPB (SendTmuxMessageResponse f1 f2) =
    HsJSONPB.pairs
      [ "success" .= f1,
        "delivery_method"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)
      ]

instance (HsJSONPB.FromJSONPB SendTmuxMessageResponse) where
  parseJSONPB =
    HsJSONPB.withObject
      "SendTmuxMessageResponse"
      ( \obj ->
          Hs.pure SendTmuxMessageResponse
            <*> obj .: "success"
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "delivery_method")
                )
      )

instance (HsJSONPB.ToJSON SendTmuxMessageResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON SendTmuxMessageResponse) where
  parseJSON = HsJSONPB.parseJSONPB

data SendMailboxMessageRequest
  = SendMailboxMessageRequest
  { sendMailboxMessageRequestRecipient :: (Hs.Maybe Effects.Events.Address),
    sendMailboxMessageRequestContent :: Hs.Text,
    sendMailboxMessageRequestSummary :: Hs.Text
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData SendMailboxMessageRequest)

instance (HsProtobuf.Named SendMailboxMessageRequest) where
  nameOf _ = Hs.fromString "SendMailboxMessageRequest"

instance (HsProtobuf.HasDefault SendMailboxMessageRequest)

instance (HsProtobuf.Message SendMailboxMessageRequest) where
  encodeMessage
    _
    SendMailboxMessageRequest
      { sendMailboxMessageRequestRecipient,
        sendMailboxMessageRequestContent,
        sendMailboxMessageRequestSummary
      } =
      Hs.mappend
        ( Hs.mappend
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 1)
                ( ( Hs.coerce
                      @(Hs.Maybe Effects.Events.Address)
                      @(HsProtobuf.Nested Effects.Events.Address)
                  )
                    sendMailboxMessageRequestRecipient
                )
            )
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 2)
                ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                    sendMailboxMessageRequestContent
                )
            )
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 3)
            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                sendMailboxMessageRequestSummary
            )
        )
  decodeMessage _ =
    Hs.pure SendMailboxMessageRequest
      <*> ( ( HsProtobuf.coerceOver
                @(HsProtobuf.Nested Effects.Events.Address)
                @(Hs.Maybe Effects.Events.Address)
            )
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 3)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        ( HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "Address"))
        )
        (HsProtobufAST.Single "recipient")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "content")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 3)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "summary")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB SendMailboxMessageRequest) where
  toJSONPB (SendMailboxMessageRequest f1 f2 f3) =
    HsJSONPB.object
      [ "recipient"
          .= ( ( Hs.coerce
                   @(Hs.Maybe Effects.Events.Address)
                   @(HsProtobuf.Nested Effects.Events.Address)
               )
                 f1
             ),
        "content"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "summary"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)
      ]
  toEncodingPB (SendMailboxMessageRequest f1 f2 f3) =
    HsJSONPB.pairs
      [ "recipient"
          .= ( ( Hs.coerce
                   @(Hs.Maybe Effects.Events.Address)
                   @(HsProtobuf.Nested Effects.Events.Address)
               )
                 f1
             ),
        "content"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "summary"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)
      ]

instance (HsJSONPB.FromJSONPB SendMailboxMessageRequest) where
  parseJSONPB =
    HsJSONPB.withObject
      "SendMailboxMessageRequest"
      ( \obj ->
          Hs.pure SendMailboxMessageRequest
            <*> ( ( HsProtobuf.coerceOver
                      @(HsProtobuf.Nested Effects.Events.Address)
                      @(Hs.Maybe Effects.Events.Address)
                  )
                    (obj .: "recipient")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "content")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "summary")
                )
      )

instance (HsJSONPB.ToJSON SendMailboxMessageRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON SendMailboxMessageRequest) where
  parseJSON = HsJSONPB.parseJSONPB

data SendMailboxMessageResponse
  = SendMailboxMessageResponse
  { sendMailboxMessageResponseSuccess :: Hs.Bool,
    sendMailboxMessageResponseDeliveryMethod :: Hs.Text
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData SendMailboxMessageResponse)

instance (HsProtobuf.Named SendMailboxMessageResponse) where
  nameOf _ = Hs.fromString "SendMailboxMessageResponse"

instance (HsProtobuf.HasDefault SendMailboxMessageResponse)

instance (HsProtobuf.Message SendMailboxMessageResponse) where
  encodeMessage
    _
    SendMailboxMessageResponse
      { sendMailboxMessageResponseSuccess,
        sendMailboxMessageResponseDeliveryMethod
      } =
      Hs.mappend
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 1)
            sendMailboxMessageResponseSuccess
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 2)
            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                sendMailboxMessageResponseDeliveryMethod
            )
        )
  decodeMessage _ =
    Hs.pure SendMailboxMessageResponse
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 1)
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.Bool)
        (HsProtobufAST.Single "success")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "delivery_method")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB SendMailboxMessageResponse) where
  toJSONPB (SendMailboxMessageResponse f1 f2) =
    HsJSONPB.object
      [ "success" .= f1,
        "delivery_method"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)
      ]
  toEncodingPB (SendMailboxMessageResponse f1 f2) =
    HsJSONPB.pairs
      [ "success" .= f1,
        "delivery_method"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)
      ]

instance (HsJSONPB.FromJSONPB SendMailboxMessageResponse) where
  parseJSONPB =
    HsJSONPB.withObject
      "SendMailboxMessageResponse"
      ( \obj ->
          Hs.pure SendMailboxMessageResponse
            <*> obj .: "success"
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "delivery_method")
                )
      )

instance (HsJSONPB.ToJSON SendMailboxMessageResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON SendMailboxMessageResponse) where
  parseJSON = HsJSONPB.parseJSONPB

data TaskBlockCause
  = TaskBlockCauseTASK_BLOCK_CAUSE_UNSPECIFIED
  | TaskBlockCauseTASK_BLOCK_CAUSE_BASE_CI_UNSTABLE
  | TaskBlockCauseTASK_BLOCK_CAUSE_EXTERNAL_DEPENDENCY
  | TaskBlockCauseTASK_BLOCK_CAUSE_SCOPE_BOUNDARY
  | TaskBlockCauseTASK_BLOCK_CAUSE_HUMAN_DECISION_REQUIRED
  | TaskBlockCauseTASK_BLOCK_CAUSE_TOOLING_UNAVAILABLE
  deriving (Hs.Show, Hs.Eq, Hs.Generic, Hs.NFData)

instance (HsProtobuf.Named TaskBlockCause) where
  nameOf _ = Hs.fromString "TaskBlockCause"

instance (HsProtobuf.HasDefault TaskBlockCause)

instance (Hs.Bounded TaskBlockCause) where
  minBound = TaskBlockCauseTASK_BLOCK_CAUSE_UNSPECIFIED
  maxBound = TaskBlockCauseTASK_BLOCK_CAUSE_TOOLING_UNAVAILABLE

instance (Hs.Ord TaskBlockCause) where
  compare x y =
    Hs.compare
      (HsProtobuf.fromProtoEnum x)
      (HsProtobuf.fromProtoEnum y)

instance (HsProtobuf.ProtoEnum TaskBlockCause) where
  toProtoEnumMay 0 =
    Hs.Just TaskBlockCauseTASK_BLOCK_CAUSE_UNSPECIFIED
  toProtoEnumMay 1 =
    Hs.Just TaskBlockCauseTASK_BLOCK_CAUSE_BASE_CI_UNSTABLE
  toProtoEnumMay 2 =
    Hs.Just TaskBlockCauseTASK_BLOCK_CAUSE_EXTERNAL_DEPENDENCY
  toProtoEnumMay 3 =
    Hs.Just TaskBlockCauseTASK_BLOCK_CAUSE_SCOPE_BOUNDARY
  toProtoEnumMay 4 =
    Hs.Just TaskBlockCauseTASK_BLOCK_CAUSE_HUMAN_DECISION_REQUIRED
  toProtoEnumMay 5 =
    Hs.Just TaskBlockCauseTASK_BLOCK_CAUSE_TOOLING_UNAVAILABLE
  toProtoEnumMay _ = Hs.Nothing
  fromProtoEnum TaskBlockCauseTASK_BLOCK_CAUSE_UNSPECIFIED = 0
  fromProtoEnum TaskBlockCauseTASK_BLOCK_CAUSE_BASE_CI_UNSTABLE = 1
  fromProtoEnum TaskBlockCauseTASK_BLOCK_CAUSE_EXTERNAL_DEPENDENCY =
    2
  fromProtoEnum TaskBlockCauseTASK_BLOCK_CAUSE_SCOPE_BOUNDARY = 3
  fromProtoEnum
    TaskBlockCauseTASK_BLOCK_CAUSE_HUMAN_DECISION_REQUIRED =
      4
  fromProtoEnum TaskBlockCauseTASK_BLOCK_CAUSE_TOOLING_UNAVAILABLE =
    5

instance (HsJSONPB.ToJSONPB TaskBlockCause) where
  toJSONPB x _ = HsJSONPB.enumFieldString x
  toEncodingPB x _ = HsJSONPB.enumFieldEncoding x

instance (HsJSONPB.FromJSONPB TaskBlockCause) where
  parseJSONPB (HsJSONPB.String "TASK_BLOCK_CAUSE_UNSPECIFIED") =
    Hs.pure TaskBlockCauseTASK_BLOCK_CAUSE_UNSPECIFIED
  parseJSONPB (HsJSONPB.String "TASK_BLOCK_CAUSE_BASE_CI_UNSTABLE") =
    Hs.pure TaskBlockCauseTASK_BLOCK_CAUSE_BASE_CI_UNSTABLE
  parseJSONPB
    (HsJSONPB.String "TASK_BLOCK_CAUSE_EXTERNAL_DEPENDENCY") =
      Hs.pure TaskBlockCauseTASK_BLOCK_CAUSE_EXTERNAL_DEPENDENCY
  parseJSONPB (HsJSONPB.String "TASK_BLOCK_CAUSE_SCOPE_BOUNDARY") =
    Hs.pure TaskBlockCauseTASK_BLOCK_CAUSE_SCOPE_BOUNDARY
  parseJSONPB
    (HsJSONPB.String "TASK_BLOCK_CAUSE_HUMAN_DECISION_REQUIRED") =
      Hs.pure TaskBlockCauseTASK_BLOCK_CAUSE_HUMAN_DECISION_REQUIRED
  parseJSONPB
    (HsJSONPB.String "TASK_BLOCK_CAUSE_TOOLING_UNAVAILABLE") =
      Hs.pure TaskBlockCauseTASK_BLOCK_CAUSE_TOOLING_UNAVAILABLE
  parseJSONPB v = HsJSONPB.typeMismatch "TaskBlockCause" v

instance (HsJSONPB.ToJSON TaskBlockCause) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON TaskBlockCause) where
  parseJSON = HsJSONPB.parseJSONPB

instance (HsProtobuf.Finite TaskBlockCause)

data TaskBlockedEvidence
  = TaskBlockedEvidence
  { taskBlockedEvidenceBaseSha :: Hs.Text,
    taskBlockedEvidenceHeadSha :: Hs.Text,
    taskBlockedEvidenceFailedChecks :: (Hs.Vector Hs.Text),
    taskBlockedEvidenceEvidenceSummary :: Hs.Text
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData TaskBlockedEvidence)

instance (HsProtobuf.Named TaskBlockedEvidence) where
  nameOf _ = Hs.fromString "TaskBlockedEvidence"

instance (HsProtobuf.HasDefault TaskBlockedEvidence)

instance (HsProtobuf.Message TaskBlockedEvidence) where
  encodeMessage
    _
    TaskBlockedEvidence
      { taskBlockedEvidenceBaseSha,
        taskBlockedEvidenceHeadSha,
        taskBlockedEvidenceFailedChecks,
        taskBlockedEvidenceEvidenceSummary
      } =
      Hs.mappend
        ( Hs.mappend
            ( Hs.mappend
                ( HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 1)
                    ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                        taskBlockedEvidenceBaseSha
                    )
                )
                ( HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 2)
                    ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                        taskBlockedEvidenceHeadSha
                    )
                )
            )
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 3)
                ( ( Hs.coerce
                      @(Hs.Vector Hs.Text)
                      @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
                  )
                    taskBlockedEvidenceFailedChecks
                )
            )
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 4)
            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                taskBlockedEvidenceEvidenceSummary
            )
        )
  decodeMessage _ =
    Hs.pure TaskBlockedEvidence
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
      <*> ( ( HsProtobuf.coerceOver
                @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
                @(Hs.Vector Hs.Text)
            )
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 3)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 4)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "base_sha")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "head_sha")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 3)
        (HsProtobufAST.Repeated HsProtobufAST.String)
        (HsProtobufAST.Single "failed_checks")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 4)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "evidence_summary")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB TaskBlockedEvidence) where
  toJSONPB (TaskBlockedEvidence f1 f2 f3 f4) =
    HsJSONPB.object
      [ "base_sha"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "head_sha"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "failed_checks"
          .= ( ( Hs.coerce
                   @(Hs.Vector Hs.Text)
                   @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
               )
                 f3
             ),
        "evidence_summary"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4)
      ]
  toEncodingPB (TaskBlockedEvidence f1 f2 f3 f4) =
    HsJSONPB.pairs
      [ "base_sha"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "head_sha"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "failed_checks"
          .= ( ( Hs.coerce
                   @(Hs.Vector Hs.Text)
                   @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
               )
                 f3
             ),
        "evidence_summary"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4)
      ]

instance (HsJSONPB.FromJSONPB TaskBlockedEvidence) where
  parseJSONPB =
    HsJSONPB.withObject
      "TaskBlockedEvidence"
      ( \obj ->
          Hs.pure TaskBlockedEvidence
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "base_sha")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "head_sha")
                )
            <*> ( ( HsProtobuf.coerceOver
                      @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
                      @(Hs.Vector Hs.Text)
                  )
                    (obj .: "failed_checks")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "evidence_summary")
                )
      )

instance (HsJSONPB.ToJSON TaskBlockedEvidence) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON TaskBlockedEvidence) where
  parseJSON = HsJSONPB.parseJSONPB

data TaskBlocked
  = TaskBlocked
  { taskBlockedCause :: (HsProtobuf.Enumerated Effects.Events.TaskBlockCause),
    taskBlockedNeedsHuman :: Hs.Bool,
    taskBlockedScopeAttribution :: Hs.Text,
    taskBlockedRetryable :: Hs.Bool,
    taskBlockedRecoveryAction :: Hs.Text,
    taskBlockedEvidence :: (Hs.Maybe Effects.Events.TaskBlockedEvidence)
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData TaskBlocked)

instance (HsProtobuf.Named TaskBlocked) where
  nameOf _ = Hs.fromString "TaskBlocked"

instance (HsProtobuf.HasDefault TaskBlocked)

instance (HsProtobuf.Message TaskBlocked) where
  encodeMessage
    _
    TaskBlocked
      { taskBlockedCause,
        taskBlockedNeedsHuman,
        taskBlockedScopeAttribution,
        taskBlockedRetryable,
        taskBlockedRecoveryAction,
        taskBlockedEvidence
      } =
      Hs.mappend
        ( Hs.mappend
            ( Hs.mappend
                ( Hs.mappend
                    ( Hs.mappend
                        ( HsProtobuf.encodeMessageField
                            (HsProtobuf.FieldNumber 1)
                            taskBlockedCause
                        )
                        ( HsProtobuf.encodeMessageField
                            (HsProtobuf.FieldNumber 2)
                            taskBlockedNeedsHuman
                        )
                    )
                    ( HsProtobuf.encodeMessageField
                        (HsProtobuf.FieldNumber 3)
                        ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                            taskBlockedScopeAttribution
                        )
                    )
                )
                ( HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 4)
                    taskBlockedRetryable
                )
            )
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 5)
                ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                    taskBlockedRecoveryAction
                )
            )
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 6)
            ( ( Hs.coerce
                  @(Hs.Maybe Effects.Events.TaskBlockedEvidence)
                  @(HsProtobuf.Nested Effects.Events.TaskBlockedEvidence)
              )
                taskBlockedEvidence
            )
        )
  decodeMessage _ =
    Hs.pure TaskBlocked
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 1)
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 2)
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 3)
              )
          )
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 4)
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 5)
              )
          )
      <*> ( ( HsProtobuf.coerceOver
                @(HsProtobuf.Nested Effects.Events.TaskBlockedEvidence)
                @(Hs.Maybe Effects.Events.TaskBlockedEvidence)
            )
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 6)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        ( HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "TaskBlockCause"))
        )
        (HsProtobufAST.Single "cause")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.Bool)
        (HsProtobufAST.Single "needs_human")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 3)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "scope_attribution")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 4)
        (HsProtobufAST.Prim HsProtobufAST.Bool)
        (HsProtobufAST.Single "retryable")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 5)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "recovery_action")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 6)
        ( HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "TaskBlockedEvidence"))
        )
        (HsProtobufAST.Single "evidence")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB TaskBlocked) where
  toJSONPB (TaskBlocked f1 f2 f3 f4 f5 f6) =
    HsJSONPB.object
      [ "cause" .= f1,
        "needs_human" .= f2,
        "scope_attribution"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
        "retryable" .= f4,
        "recovery_action"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f5),
        "evidence"
          .= ( ( Hs.coerce
                   @(Hs.Maybe Effects.Events.TaskBlockedEvidence)
                   @(HsProtobuf.Nested Effects.Events.TaskBlockedEvidence)
               )
                 f6
             )
      ]
  toEncodingPB (TaskBlocked f1 f2 f3 f4 f5 f6) =
    HsJSONPB.pairs
      [ "cause" .= f1,
        "needs_human" .= f2,
        "scope_attribution"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
        "retryable" .= f4,
        "recovery_action"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f5),
        "evidence"
          .= ( ( Hs.coerce
                   @(Hs.Maybe Effects.Events.TaskBlockedEvidence)
                   @(HsProtobuf.Nested Effects.Events.TaskBlockedEvidence)
               )
                 f6
             )
      ]

instance (HsJSONPB.FromJSONPB TaskBlocked) where
  parseJSONPB =
    HsJSONPB.withObject
      "TaskBlocked"
      ( \obj ->
          Hs.pure TaskBlocked
            <*> obj .: "cause"
            <*> obj .: "needs_human"
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "scope_attribution")
                )
            <*> obj .: "retryable"
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "recovery_action")
                )
            <*> ( ( HsProtobuf.coerceOver
                      @(HsProtobuf.Nested Effects.Events.TaskBlockedEvidence)
                      @(Hs.Maybe Effects.Events.TaskBlockedEvidence)
                  )
                    (obj .: "evidence")
                )
      )

instance (HsJSONPB.ToJSON TaskBlocked) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON TaskBlocked) where
  parseJSON = HsJSONPB.parseJSONPB

data NotifyParentRequest
  = NotifyParentRequest
  { notifyParentRequestStatus :: Hs.Text,
    notifyParentRequestMessage :: Hs.Text,
    notifyParentRequestAgentId :: Hs.Text,
    notifyParentRequestOverrideRecipient :: (Hs.Maybe Effects.Events.Address),
    notifyParentRequestTaskOutcome :: (Hs.Maybe NotifyParentRequestTaskOutcome)
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData NotifyParentRequest)

instance (HsProtobuf.Named NotifyParentRequest) where
  nameOf _ = Hs.fromString "NotifyParentRequest"

instance (HsProtobuf.HasDefault NotifyParentRequest)

instance (HsProtobuf.Message NotifyParentRequest) where
  encodeMessage
    _
    NotifyParentRequest
      { notifyParentRequestStatus,
        notifyParentRequestMessage,
        notifyParentRequestAgentId,
        notifyParentRequestOverrideRecipient,
        notifyParentRequestTaskOutcome
      } =
      Hs.mappend
        ( Hs.mappend
            ( Hs.mappend
                ( Hs.mappend
                    ( HsProtobuf.encodeMessageField
                        (HsProtobuf.FieldNumber 1)
                        ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                            notifyParentRequestStatus
                        )
                    )
                    ( HsProtobuf.encodeMessageField
                        (HsProtobuf.FieldNumber 2)
                        ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                            notifyParentRequestMessage
                        )
                    )
                )
                ( HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 3)
                    ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                        notifyParentRequestAgentId
                    )
                )
            )
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 4)
                ( ( Hs.coerce
                      @(Hs.Maybe Effects.Events.Address)
                      @(HsProtobuf.Nested Effects.Events.Address)
                  )
                    notifyParentRequestOverrideRecipient
                )
            )
        )
        ( case notifyParentRequestTaskOutcome of
            Hs.Nothing -> Hs.mempty
            Hs.Just x ->
              case x of
                NotifyParentRequestTaskOutcomeBlocked y ->
                  HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 5)
                    ( ( Hs.coerce
                          @(Hs.Maybe Effects.Events.TaskBlocked)
                          @(HsProtobuf.Nested Effects.Events.TaskBlocked)
                      )
                        (Hs.Just y)
                    )
        )
  decodeMessage _ =
    Hs.pure NotifyParentRequest
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 3)
              )
          )
      <*> ( ( HsProtobuf.coerceOver
                @(HsProtobuf.Nested Effects.Events.Address)
                @(Hs.Maybe Effects.Events.Address)
            )
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 4)
              )
          )
      <*> HsProtobuf.oneof
        Hs.Nothing
        [ ( (HsProtobuf.FieldNumber 5),
            Hs.pure (Hs.fmap NotifyParentRequestTaskOutcomeBlocked)
              <*> ( ( HsProtobuf.coerceOver
                        @(HsProtobuf.Nested Effects.Events.TaskBlocked)
                        @(Hs.Maybe Effects.Events.TaskBlocked)
                    )
                      HsProtobuf.decodeMessageField
                  )
          )
        ]
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "status")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "message")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 3)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "agent_id")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 4)
        ( HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "Address"))
        )
        (HsProtobufAST.Single "override_recipient")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB NotifyParentRequest) where
  toJSONPB (NotifyParentRequest f1 f2 f3 f4 f5) =
    HsJSONPB.object
      [ "status"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "message"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "agent_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
        "override_recipient"
          .= ( ( Hs.coerce
                   @(Hs.Maybe Effects.Events.Address)
                   @(HsProtobuf.Nested Effects.Events.Address)
               )
                 f4
             ),
        ( let encodeTask_outcome =
                ( case f5 of
                    Hs.Just (NotifyParentRequestTaskOutcomeBlocked f5) ->
                      HsJSONPB.pair "blocked" f5
                    Hs.Nothing -> Hs.mempty
                )
           in ( \options ->
                  if HsJSONPB.optEmitNamedOneof options
                    then
                      ( "task_outcome"
                          .= HsJSONPB.objectOrNull [encodeTask_outcome] options
                      )
                        options
                    else
                      encodeTask_outcome options
              )
        )
      ]
  toEncodingPB (NotifyParentRequest f1 f2 f3 f4 f5) =
    HsJSONPB.pairs
      [ "status"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "message"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "agent_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
        "override_recipient"
          .= ( ( Hs.coerce
                   @(Hs.Maybe Effects.Events.Address)
                   @(HsProtobuf.Nested Effects.Events.Address)
               )
                 f4
             ),
        ( let encodeTask_outcome =
                ( case f5 of
                    Hs.Just (NotifyParentRequestTaskOutcomeBlocked f5) ->
                      HsJSONPB.pair "blocked" f5
                    Hs.Nothing -> Hs.mempty
                )
           in ( \options ->
                  if HsJSONPB.optEmitNamedOneof options
                    then
                      ( "task_outcome"
                          .= HsJSONPB.pairsOrNull [encodeTask_outcome] options
                      )
                        options
                    else
                      encodeTask_outcome options
              )
        )
      ]

instance (HsJSONPB.FromJSONPB NotifyParentRequest) where
  parseJSONPB =
    HsJSONPB.withObject
      "NotifyParentRequest"
      ( \obj ->
          Hs.pure NotifyParentRequest
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "status")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "message")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "agent_id")
                )
            <*> ( ( HsProtobuf.coerceOver
                      @(HsProtobuf.Nested Effects.Events.Address)
                      @(Hs.Maybe Effects.Events.Address)
                  )
                    (obj .: "override_recipient")
                )
            <*> ( let parseTask_outcome parseObj =
                        Hs.msum
                          [ Hs.Just Hs.. NotifyParentRequestTaskOutcomeBlocked
                              <$> HsJSONPB.parseField parseObj "blocked",
                            Hs.pure Hs.Nothing
                          ]
                   in ( obj .: "task_outcome"
                          Hs.>>= HsJSONPB.withObject "task_outcome" parseTask_outcome
                      )
                        <|> (parseTask_outcome obj)
                )
      )

instance (HsJSONPB.ToJSON NotifyParentRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON NotifyParentRequest) where
  parseJSON = HsJSONPB.parseJSONPB

newtype NotifyParentRequestTaskOutcome
  = NotifyParentRequestTaskOutcomeBlocked Effects.Events.TaskBlocked
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData NotifyParentRequestTaskOutcome)

instance (HsProtobuf.Named NotifyParentRequestTaskOutcome) where
  nameOf _ = Hs.fromString "NotifyParentRequestTaskOutcome"

newtype NotifyParentResponse
  = NotifyParentResponse {notifyParentResponseAck :: Hs.Bool}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData NotifyParentResponse)

instance (HsProtobuf.Named NotifyParentResponse) where
  nameOf _ = Hs.fromString "NotifyParentResponse"

instance (HsProtobuf.HasDefault NotifyParentResponse)

instance (HsProtobuf.Message NotifyParentResponse) where
  encodeMessage _ NotifyParentResponse {notifyParentResponseAck} =
    ( HsProtobuf.encodeMessageField
        (HsProtobuf.FieldNumber 1)
        notifyParentResponseAck
    )
  decodeMessage _ =
    Hs.pure NotifyParentResponse
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 1)
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.Bool)
        (HsProtobufAST.Single "ack")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB NotifyParentResponse) where
  toJSONPB (NotifyParentResponse f1) = HsJSONPB.object ["ack" .= f1]
  toEncodingPB (NotifyParentResponse f1) =
    HsJSONPB.pairs ["ack" .= f1]

instance (HsJSONPB.FromJSONPB NotifyParentResponse) where
  parseJSONPB =
    HsJSONPB.withObject
      "NotifyParentResponse"
      (\obj -> Hs.pure NotifyParentResponse <*> obj .: "ack")

instance (HsJSONPB.ToJSON NotifyParentResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON NotifyParentResponse) where
  parseJSON = HsJSONPB.parseJSONPB
