{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE NegativeLiterals #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
{-# OPTIONS_GHC -fno-warn-missing-export-lists #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-- | Generated by Haskell protocol buffer compiler. DO NOT EDIT!
module Effects.Inbox where

import Control.Applicative ((<$>), (<*>), (<|>))
import Control.Applicative qualified as Hs
import Control.DeepSeq qualified as Hs
import Control.Monad qualified as Hs
import Data.ByteString qualified as Hs
import Data.Coerce qualified as Hs
import Data.Int qualified as Hs (Int16, Int32, Int64)
import Data.List.NonEmpty qualified as Hs (NonEmpty (..))
import Data.Map qualified as Hs (Map, mapKeysMonotonic)
import Data.Proxy qualified as Proxy
import Data.String qualified as Hs (fromString)
import Data.Text.Lazy qualified as Hs (Text)
import Data.Vector qualified as Hs (Vector)
import Data.Word qualified as Hs (Word16, Word32, Word64)
import GHC.Enum qualified as Hs
import GHC.Generics qualified as Hs
import Google.Protobuf.Wrappers.Polymorphic qualified as HsProtobuf
  ( Wrapped (..),
  )
import Proto3.Suite.Class qualified as HsProtobuf
import Proto3.Suite.DotProto qualified as HsProtobufAST
import Proto3.Suite.JSONPB ((.:), (.=))
import Proto3.Suite.JSONPB qualified as HsJSONPB
import Proto3.Suite.Types qualified as HsProtobuf
import Proto3.Wire qualified as HsProtobuf
import Proto3.Wire.Decode qualified as HsProtobuf
  ( Parser,
    RawField,
  )
import Unsafe.Coerce qualified as Hs
import Prelude qualified as Hs

data InboxCheckEffect
  = InboxCheckEffect {}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData InboxCheckEffect)

instance (HsProtobuf.Named InboxCheckEffect) where
  nameOf _ = Hs.fromString "InboxCheckEffect"

instance (HsProtobuf.HasDefault InboxCheckEffect)

instance (HsProtobuf.Message InboxCheckEffect) where
  encodeMessage _ InboxCheckEffect {} = Hs.mempty
  decodeMessage _ = Hs.pure InboxCheckEffect
  dotProto _ = []

instance (HsJSONPB.ToJSONPB InboxCheckEffect) where
  toJSONPB InboxCheckEffect = HsJSONPB.object []
  toEncodingPB InboxCheckEffect = HsJSONPB.pairs []

instance (HsJSONPB.FromJSONPB InboxCheckEffect) where
  parseJSONPB =
    HsJSONPB.withObject
      "InboxCheckEffect"
      (\obj -> Hs.pure InboxCheckEffect)

instance (HsJSONPB.ToJSON InboxCheckEffect) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON InboxCheckEffect) where
  parseJSON = HsJSONPB.parseJSONPB

data InboxMessage
  = InboxMessage
  { inboxMessageFromAgent :: Hs.Text,
    inboxMessageContent :: Hs.Text,
    inboxMessageSummary :: Hs.Text,
    inboxMessageCreatedAt :: Hs.Int64
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData InboxMessage)

instance (HsProtobuf.Named InboxMessage) where
  nameOf _ = Hs.fromString "InboxMessage"

instance (HsProtobuf.HasDefault InboxMessage)

instance (HsProtobuf.Message InboxMessage) where
  encodeMessage
    _
    InboxMessage
      { inboxMessageFromAgent,
        inboxMessageContent,
        inboxMessageSummary,
        inboxMessageCreatedAt
      } =
      Hs.mappend
        ( Hs.mappend
            ( Hs.mappend
                ( HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 1)
                    ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                        inboxMessageFromAgent
                    )
                )
                ( HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 2)
                    ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                        inboxMessageContent
                    )
                )
            )
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 3)
                ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                    inboxMessageSummary
                )
            )
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 4)
            inboxMessageCreatedAt
        )
  decodeMessage _ =
    Hs.pure InboxMessage
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 3)
              )
          )
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 4)
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "from_agent")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "content")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 3)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "summary")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 4)
        (HsProtobufAST.Prim HsProtobufAST.Int64)
        (HsProtobufAST.Single "created_at")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB InboxMessage) where
  toJSONPB (InboxMessage f1 f2 f3 f4) =
    HsJSONPB.object
      [ "from_agent"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "content"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "summary"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
        "created_at" .= f4
      ]
  toEncodingPB (InboxMessage f1 f2 f3 f4) =
    HsJSONPB.pairs
      [ "from_agent"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "content"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "summary"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
        "created_at" .= f4
      ]

instance (HsJSONPB.FromJSONPB InboxMessage) where
  parseJSONPB =
    HsJSONPB.withObject
      "InboxMessage"
      ( \obj ->
          Hs.pure InboxMessage
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "from_agent")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "content")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "summary")
                )
            <*> obj .: "created_at"
      )

instance (HsJSONPB.ToJSON InboxMessage) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON InboxMessage) where
  parseJSON = HsJSONPB.parseJSONPB

newtype InboxCheckResult
  = InboxCheckResult {inboxCheckResultMessages :: (Hs.Vector Effects.Inbox.InboxMessage)}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData InboxCheckResult)

instance (HsProtobuf.Named InboxCheckResult) where
  nameOf _ = Hs.fromString "InboxCheckResult"

instance (HsProtobuf.HasDefault InboxCheckResult)

instance (HsProtobuf.Message InboxCheckResult) where
  encodeMessage _ InboxCheckResult {inboxCheckResultMessages} =
    ( HsProtobuf.encodeMessageField
        (HsProtobuf.FieldNumber 1)
        ( ( Hs.coerce
              @(Hs.Vector Effects.Inbox.InboxMessage)
              @(HsProtobuf.NestedVec Effects.Inbox.InboxMessage)
          )
            inboxCheckResultMessages
        )
    )
  decodeMessage _ =
    Hs.pure InboxCheckResult
      <*> ( ( HsProtobuf.coerceOver
                @(HsProtobuf.NestedVec Effects.Inbox.InboxMessage)
                @(Hs.Vector Effects.Inbox.InboxMessage)
            )
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        ( HsProtobufAST.Repeated
            (HsProtobufAST.Named (HsProtobufAST.Single "InboxMessage"))
        )
        (HsProtobufAST.Single "messages")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB InboxCheckResult) where
  toJSONPB (InboxCheckResult f1) =
    HsJSONPB.object
      [ "messages"
          .= ( ( Hs.coerce
                   @(Hs.Vector Effects.Inbox.InboxMessage)
                   @(HsProtobuf.NestedVec Effects.Inbox.InboxMessage)
               )
                 f1
             )
      ]
  toEncodingPB (InboxCheckResult f1) =
    HsJSONPB.pairs
      [ "messages"
          .= ( ( Hs.coerce
                   @(Hs.Vector Effects.Inbox.InboxMessage)
                   @(HsProtobuf.NestedVec Effects.Inbox.InboxMessage)
               )
                 f1
             )
      ]

instance (HsJSONPB.FromJSONPB InboxCheckResult) where
  parseJSONPB =
    HsJSONPB.withObject
      "InboxCheckResult"
      ( \obj ->
          Hs.pure InboxCheckResult
            <*> ( ( HsProtobuf.coerceOver
                      @(HsProtobuf.NestedVec Effects.Inbox.InboxMessage)
                      @(Hs.Vector Effects.Inbox.InboxMessage)
                  )
                    (obj .: "messages")
                )
      )

instance (HsJSONPB.ToJSON InboxCheckResult) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON InboxCheckResult) where
  parseJSON = HsJSONPB.parseJSONPB
