{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE NegativeLiterals #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
{-# OPTIONS_GHC -fno-warn-missing-export-lists #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-- | Generated by Haskell protocol buffer compiler. DO NOT EDIT!
module Effects.Lifecycle where

import Control.Applicative ((<$>), (<*>), (<|>))
import Control.Applicative qualified as Hs
import Control.DeepSeq qualified as Hs
import Control.Monad qualified as Hs
import Data.ByteString qualified as Hs
import Data.Coerce qualified as Hs
import Data.Int qualified as Hs (Int16, Int32, Int64)
import Data.List.NonEmpty qualified as Hs (NonEmpty (..))
import Data.Map qualified as Hs (Map, mapKeysMonotonic)
import Data.Proxy qualified as Proxy
import Data.String qualified as Hs (fromString)
import Data.Text.Lazy qualified as Hs (Text)
import Data.Vector qualified as Hs (Vector)
import Data.Word qualified as Hs (Word16, Word32, Word64)
import Effects.Agent qualified
import GHC.Enum qualified as Hs
import GHC.Generics qualified as Hs
import Google.Protobuf.Wrappers.Polymorphic qualified as HsProtobuf
  ( Wrapped (..),
  )
import Proto3.Suite.Class qualified as HsProtobuf
import Proto3.Suite.DotProto qualified as HsProtobufAST
import Proto3.Suite.JSONPB ((.:), (.=))
import Proto3.Suite.JSONPB qualified as HsJSONPB
import Proto3.Suite.Types qualified as HsProtobuf
import Proto3.Wire qualified as HsProtobuf
import Proto3.Wire.Decode qualified as HsProtobuf
  ( Parser,
    RawField,
  )
import Unsafe.Coerce qualified as Hs
import Prelude qualified as Hs

data HasPendingWorkEffect
  = HasPendingWorkEffect {}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData HasPendingWorkEffect)

instance (HsProtobuf.Named HasPendingWorkEffect) where
  nameOf _ = Hs.fromString "HasPendingWorkEffect"

instance (HsProtobuf.HasDefault HasPendingWorkEffect)

instance (HsProtobuf.Message HasPendingWorkEffect) where
  encodeMessage _ HasPendingWorkEffect {} = Hs.mempty
  decodeMessage _ = Hs.pure HasPendingWorkEffect
  dotProto _ = []

instance (HsJSONPB.ToJSONPB HasPendingWorkEffect) where
  toJSONPB HasPendingWorkEffect = HsJSONPB.object []
  toEncodingPB HasPendingWorkEffect = HsJSONPB.pairs []

instance (HsJSONPB.FromJSONPB HasPendingWorkEffect) where
  parseJSONPB =
    HsJSONPB.withObject
      "HasPendingWorkEffect"
      (\obj -> Hs.pure HasPendingWorkEffect)

instance (HsJSONPB.ToJSON HasPendingWorkEffect) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON HasPendingWorkEffect) where
  parseJSON = HsJSONPB.parseJSONPB

data HasPendingWorkResult
  = HasPendingWorkResult
  { hasPendingWorkResultHasPendingWork :: Hs.Bool,
    hasPendingWorkResultOpenIssueCount :: Hs.Int32,
    hasPendingWorkResultAliveAgentCount :: Hs.Int32,
    hasPendingWorkResultAliveAgents :: (Hs.Vector Effects.Agent.AgentInfo)
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData HasPendingWorkResult)

instance (HsProtobuf.Named HasPendingWorkResult) where
  nameOf _ = Hs.fromString "HasPendingWorkResult"

instance (HsProtobuf.HasDefault HasPendingWorkResult)

instance (HsProtobuf.Message HasPendingWorkResult) where
  encodeMessage
    _
    HasPendingWorkResult
      { hasPendingWorkResultHasPendingWork,
        hasPendingWorkResultOpenIssueCount,
        hasPendingWorkResultAliveAgentCount,
        hasPendingWorkResultAliveAgents
      } =
      Hs.mappend
        ( Hs.mappend
            ( Hs.mappend
                ( HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 1)
                    hasPendingWorkResultHasPendingWork
                )
                ( HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 2)
                    hasPendingWorkResultOpenIssueCount
                )
            )
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 3)
                hasPendingWorkResultAliveAgentCount
            )
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 4)
            ( ( Hs.coerce
                  @(Hs.Vector Effects.Agent.AgentInfo)
                  @(HsProtobuf.NestedVec Effects.Agent.AgentInfo)
              )
                hasPendingWorkResultAliveAgents
            )
        )
  decodeMessage _ =
    Hs.pure HasPendingWorkResult
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 1)
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 2)
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 3)
      <*> ( ( HsProtobuf.coerceOver
                @(HsProtobuf.NestedVec Effects.Agent.AgentInfo)
                @(Hs.Vector Effects.Agent.AgentInfo)
            )
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 4)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.Bool)
        (HsProtobufAST.Single "has_pending_work")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.Int32)
        (HsProtobufAST.Single "open_issue_count")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 3)
        (HsProtobufAST.Prim HsProtobufAST.Int32)
        (HsProtobufAST.Single "alive_agent_count")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 4)
        ( HsProtobufAST.Repeated
            ( HsProtobufAST.Named
                ( HsProtobufAST.Dots
                    ( HsProtobufAST.Path
                        ("exomonad" Hs.:| ["effects", "agent", "AgentInfo"])
                    )
                )
            )
        )
        (HsProtobufAST.Single "alive_agents")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB HasPendingWorkResult) where
  toJSONPB (HasPendingWorkResult f1 f2 f3 f4) =
    HsJSONPB.object
      [ "has_pending_work" .= f1,
        "open_issue_count" .= f2,
        "alive_agent_count" .= f3,
        "alive_agents"
          .= ( ( Hs.coerce
                   @(Hs.Vector Effects.Agent.AgentInfo)
                   @(HsProtobuf.NestedVec Effects.Agent.AgentInfo)
               )
                 f4
             )
      ]
  toEncodingPB (HasPendingWorkResult f1 f2 f3 f4) =
    HsJSONPB.pairs
      [ "has_pending_work" .= f1,
        "open_issue_count" .= f2,
        "alive_agent_count" .= f3,
        "alive_agents"
          .= ( ( Hs.coerce
                   @(Hs.Vector Effects.Agent.AgentInfo)
                   @(HsProtobuf.NestedVec Effects.Agent.AgentInfo)
               )
                 f4
             )
      ]

instance (HsJSONPB.FromJSONPB HasPendingWorkResult) where
  parseJSONPB =
    HsJSONPB.withObject
      "HasPendingWorkResult"
      ( \obj ->
          Hs.pure HasPendingWorkResult
            <*> obj .: "has_pending_work"
            <*> obj .: "open_issue_count"
            <*> obj .: "alive_agent_count"
            <*> ( ( HsProtobuf.coerceOver
                      @(HsProtobuf.NestedVec Effects.Agent.AgentInfo)
                      @(Hs.Vector Effects.Agent.AgentInfo)
                  )
                    (obj .: "alive_agents")
                )
      )

instance (HsJSONPB.ToJSON HasPendingWorkResult) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON HasPendingWorkResult) where
  parseJSON = HsJSONPB.parseJSONPB

data ServerShutdownEffect
  = ServerShutdownEffect {}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData ServerShutdownEffect)

instance (HsProtobuf.Named ServerShutdownEffect) where
  nameOf _ = Hs.fromString "ServerShutdownEffect"

instance (HsProtobuf.HasDefault ServerShutdownEffect)

instance (HsProtobuf.Message ServerShutdownEffect) where
  encodeMessage _ ServerShutdownEffect {} = Hs.mempty
  decodeMessage _ = Hs.pure ServerShutdownEffect
  dotProto _ = []

instance (HsJSONPB.ToJSONPB ServerShutdownEffect) where
  toJSONPB ServerShutdownEffect = HsJSONPB.object []
  toEncodingPB ServerShutdownEffect = HsJSONPB.pairs []

instance (HsJSONPB.FromJSONPB ServerShutdownEffect) where
  parseJSONPB =
    HsJSONPB.withObject
      "ServerShutdownEffect"
      (\obj -> Hs.pure ServerShutdownEffect)

instance (HsJSONPB.ToJSON ServerShutdownEffect) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON ServerShutdownEffect) where
  parseJSON = HsJSONPB.parseJSONPB

data ServerShutdownResult
  = ServerShutdownResult
  { serverShutdownResultSuccess :: Hs.Bool,
    serverShutdownResultError :: Hs.Text,
    serverShutdownResultMessage :: Hs.Text
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData ServerShutdownResult)

instance (HsProtobuf.Named ServerShutdownResult) where
  nameOf _ = Hs.fromString "ServerShutdownResult"

instance (HsProtobuf.HasDefault ServerShutdownResult)

instance (HsProtobuf.Message ServerShutdownResult) where
  encodeMessage
    _
    ServerShutdownResult
      { serverShutdownResultSuccess,
        serverShutdownResultError,
        serverShutdownResultMessage
      } =
      Hs.mappend
        ( Hs.mappend
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 1)
                serverShutdownResultSuccess
            )
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 2)
                ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                    serverShutdownResultError
                )
            )
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 3)
            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                serverShutdownResultMessage
            )
        )
  decodeMessage _ =
    Hs.pure ServerShutdownResult
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 1)
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 3)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.Bool)
        (HsProtobufAST.Single "success")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "error")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 3)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "message")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB ServerShutdownResult) where
  toJSONPB (ServerShutdownResult f1 f2 f3) =
    HsJSONPB.object
      [ "success" .= f1,
        "error" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "message"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)
      ]
  toEncodingPB (ServerShutdownResult f1 f2 f3) =
    HsJSONPB.pairs
      [ "success" .= f1,
        "error" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "message"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)
      ]

instance (HsJSONPB.FromJSONPB ServerShutdownResult) where
  parseJSONPB =
    HsJSONPB.withObject
      "ServerShutdownResult"
      ( \obj ->
          Hs.pure ServerShutdownResult
            <*> obj .: "success"
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "error")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "message")
                )
      )

instance (HsJSONPB.ToJSON ServerShutdownResult) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON ServerShutdownResult) where
  parseJSON = HsJSONPB.parseJSONPB
