{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE NegativeLiterals #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
{-# OPTIONS_GHC -fno-warn-missing-export-lists #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-- | Generated by Haskell protocol buffer compiler. DO NOT EDIT!
module Effects.Memory where

import Control.Applicative ((<$>), (<*>), (<|>))
import Control.Applicative qualified as Hs
import Control.DeepSeq qualified as Hs
import Control.Monad qualified as Hs
import Data.ByteString qualified as Hs
import Data.Coerce qualified as Hs
import Data.Int qualified as Hs (Int16, Int32, Int64)
import Data.List.NonEmpty qualified as Hs (NonEmpty (..))
import Data.Map qualified as Hs (Map, mapKeysMonotonic)
import Data.Proxy qualified as Proxy
import Data.String qualified as Hs (fromString)
import Data.Text.Lazy qualified as Hs (Text)
import Data.Vector qualified as Hs (Vector)
import Data.Word qualified as Hs (Word16, Word32, Word64)
import GHC.Enum qualified as Hs
import GHC.Generics qualified as Hs
import Google.Protobuf.Wrappers.Polymorphic qualified as HsProtobuf
  ( Wrapped (..),
  )
import Proto3.Suite.Class qualified as HsProtobuf
import Proto3.Suite.DotProto qualified as HsProtobufAST
import Proto3.Suite.JSONPB ((.:), (.=))
import Proto3.Suite.JSONPB qualified as HsJSONPB
import Proto3.Suite.Types qualified as HsProtobuf
import Proto3.Wire qualified as HsProtobuf
import Proto3.Wire.Decode qualified as HsProtobuf
  ( Parser,
    RawField,
  )
import Unsafe.Coerce qualified as Hs
import Prelude qualified as Hs

data MemoryKind
  = MemoryKindMEMORY_KIND_UNSPECIFIED
  | MemoryKindORIGINAL_PLAN
  | MemoryKindWAVE_PLAN
  | MemoryKindSPAWNED_CHILD
  | MemoryKindCHILD_HANDOFF
  | MemoryKindBLOCKER
  | MemoryKindDECISION
  | MemoryKindREVIEW_FEEDBACK
  | MemoryKindFIX_DIRECTION
  | MemoryKindMERGE_RESULT
  | MemoryKindCI_RESULT
  | MemoryKindNEXT_ACTION
  | MemoryKindHUMAN_CLARIFICATION
  | MemoryKindSESSION_SUMMARY
  | MemoryKindTURN_END
  deriving (Hs.Show, Hs.Eq, Hs.Generic, Hs.NFData)

instance (HsProtobuf.Named MemoryKind) where
  nameOf _ = Hs.fromString "MemoryKind"

instance (HsProtobuf.HasDefault MemoryKind)

instance (Hs.Bounded MemoryKind) where
  minBound = MemoryKindMEMORY_KIND_UNSPECIFIED
  maxBound = MemoryKindTURN_END

instance (Hs.Ord MemoryKind) where
  compare x y =
    Hs.compare
      (HsProtobuf.fromProtoEnum x)
      (HsProtobuf.fromProtoEnum y)

instance (HsProtobuf.ProtoEnum MemoryKind) where
  toProtoEnumMay 0 = Hs.Just MemoryKindMEMORY_KIND_UNSPECIFIED
  toProtoEnumMay 1 = Hs.Just MemoryKindORIGINAL_PLAN
  toProtoEnumMay 2 = Hs.Just MemoryKindWAVE_PLAN
  toProtoEnumMay 3 = Hs.Just MemoryKindSPAWNED_CHILD
  toProtoEnumMay 4 = Hs.Just MemoryKindCHILD_HANDOFF
  toProtoEnumMay 5 = Hs.Just MemoryKindBLOCKER
  toProtoEnumMay 6 = Hs.Just MemoryKindDECISION
  toProtoEnumMay 7 = Hs.Just MemoryKindREVIEW_FEEDBACK
  toProtoEnumMay 8 = Hs.Just MemoryKindFIX_DIRECTION
  toProtoEnumMay 9 = Hs.Just MemoryKindMERGE_RESULT
  toProtoEnumMay 10 = Hs.Just MemoryKindCI_RESULT
  toProtoEnumMay 11 = Hs.Just MemoryKindNEXT_ACTION
  toProtoEnumMay 12 = Hs.Just MemoryKindHUMAN_CLARIFICATION
  toProtoEnumMay 13 = Hs.Just MemoryKindSESSION_SUMMARY
  toProtoEnumMay 14 = Hs.Just MemoryKindTURN_END
  toProtoEnumMay _ = Hs.Nothing
  fromProtoEnum MemoryKindMEMORY_KIND_UNSPECIFIED = 0
  fromProtoEnum MemoryKindORIGINAL_PLAN = 1
  fromProtoEnum MemoryKindWAVE_PLAN = 2
  fromProtoEnum MemoryKindSPAWNED_CHILD = 3
  fromProtoEnum MemoryKindCHILD_HANDOFF = 4
  fromProtoEnum MemoryKindBLOCKER = 5
  fromProtoEnum MemoryKindDECISION = 6
  fromProtoEnum MemoryKindREVIEW_FEEDBACK = 7
  fromProtoEnum MemoryKindFIX_DIRECTION = 8
  fromProtoEnum MemoryKindMERGE_RESULT = 9
  fromProtoEnum MemoryKindCI_RESULT = 10
  fromProtoEnum MemoryKindNEXT_ACTION = 11
  fromProtoEnum MemoryKindHUMAN_CLARIFICATION = 12
  fromProtoEnum MemoryKindSESSION_SUMMARY = 13
  fromProtoEnum MemoryKindTURN_END = 14

instance (HsJSONPB.ToJSONPB MemoryKind) where
  toJSONPB x _ = HsJSONPB.enumFieldString x
  toEncodingPB x _ = HsJSONPB.enumFieldEncoding x

instance (HsJSONPB.FromJSONPB MemoryKind) where
  parseJSONPB (HsJSONPB.String "MEMORY_KIND_UNSPECIFIED") =
    Hs.pure MemoryKindMEMORY_KIND_UNSPECIFIED
  parseJSONPB (HsJSONPB.String "ORIGINAL_PLAN") =
    Hs.pure MemoryKindORIGINAL_PLAN
  parseJSONPB (HsJSONPB.String "WAVE_PLAN") =
    Hs.pure MemoryKindWAVE_PLAN
  parseJSONPB (HsJSONPB.String "SPAWNED_CHILD") =
    Hs.pure MemoryKindSPAWNED_CHILD
  parseJSONPB (HsJSONPB.String "CHILD_HANDOFF") =
    Hs.pure MemoryKindCHILD_HANDOFF
  parseJSONPB (HsJSONPB.String "BLOCKER") = Hs.pure MemoryKindBLOCKER
  parseJSONPB (HsJSONPB.String "DECISION") =
    Hs.pure MemoryKindDECISION
  parseJSONPB (HsJSONPB.String "REVIEW_FEEDBACK") =
    Hs.pure MemoryKindREVIEW_FEEDBACK
  parseJSONPB (HsJSONPB.String "FIX_DIRECTION") =
    Hs.pure MemoryKindFIX_DIRECTION
  parseJSONPB (HsJSONPB.String "MERGE_RESULT") =
    Hs.pure MemoryKindMERGE_RESULT
  parseJSONPB (HsJSONPB.String "CI_RESULT") =
    Hs.pure MemoryKindCI_RESULT
  parseJSONPB (HsJSONPB.String "NEXT_ACTION") =
    Hs.pure MemoryKindNEXT_ACTION
  parseJSONPB (HsJSONPB.String "HUMAN_CLARIFICATION") =
    Hs.pure MemoryKindHUMAN_CLARIFICATION
  parseJSONPB (HsJSONPB.String "SESSION_SUMMARY") =
    Hs.pure MemoryKindSESSION_SUMMARY
  parseJSONPB (HsJSONPB.String "TURN_END") =
    Hs.pure MemoryKindTURN_END
  parseJSONPB v = HsJSONPB.typeMismatch "MemoryKind" v

instance (HsJSONPB.ToJSON MemoryKind) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON MemoryKind) where
  parseJSON = HsJSONPB.parseJSONPB

instance (HsProtobuf.Finite MemoryKind)

data MemoryRecord
  = MemoryRecord
  { memoryRecordId :: Hs.Int64,
    memoryRecordRunId :: Hs.Text,
    memoryRecordAgentId :: Hs.Text,
    memoryRecordBirthBranch :: Hs.Text,
    memoryRecordIssueId :: Hs.Int64,
    memoryRecordKind :: (HsProtobuf.Enumerated Effects.Memory.MemoryKind),
    memoryRecordImportance :: Hs.Int32,
    memoryRecordSummary :: Hs.Text,
    memoryRecordDetail :: Hs.Text,
    memoryRecordCreatedAt :: Hs.Int64,
    memoryRecordSupersedesId :: Hs.Int64,
    memoryRecordMetadataJson :: Hs.Text
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData MemoryRecord)

instance (HsProtobuf.Named MemoryRecord) where
  nameOf _ = Hs.fromString "MemoryRecord"

instance (HsProtobuf.HasDefault MemoryRecord)

instance (HsProtobuf.Message MemoryRecord) where
  encodeMessage
    _
    MemoryRecord
      { memoryRecordId,
        memoryRecordRunId,
        memoryRecordAgentId,
        memoryRecordBirthBranch,
        memoryRecordIssueId,
        memoryRecordKind,
        memoryRecordImportance,
        memoryRecordSummary,
        memoryRecordDetail,
        memoryRecordCreatedAt,
        memoryRecordSupersedesId,
        memoryRecordMetadataJson
      } =
      Hs.mappend
        ( Hs.mappend
            ( Hs.mappend
                ( Hs.mappend
                    ( Hs.mappend
                        ( Hs.mappend
                            ( Hs.mappend
                                ( Hs.mappend
                                    ( Hs.mappend
                                        ( Hs.mappend
                                            ( Hs.mappend
                                                ( HsProtobuf.encodeMessageField
                                                    (HsProtobuf.FieldNumber 1)
                                                    memoryRecordId
                                                )
                                                ( HsProtobuf.encodeMessageField
                                                    (HsProtobuf.FieldNumber 2)
                                                    ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                                                        memoryRecordRunId
                                                    )
                                                )
                                            )
                                            ( HsProtobuf.encodeMessageField
                                                (HsProtobuf.FieldNumber 3)
                                                ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                                                    memoryRecordAgentId
                                                )
                                            )
                                        )
                                        ( HsProtobuf.encodeMessageField
                                            (HsProtobuf.FieldNumber 4)
                                            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                                                memoryRecordBirthBranch
                                            )
                                        )
                                    )
                                    ( HsProtobuf.encodeMessageField
                                        (HsProtobuf.FieldNumber 5)
                                        memoryRecordIssueId
                                    )
                                )
                                ( HsProtobuf.encodeMessageField
                                    (HsProtobuf.FieldNumber 6)
                                    memoryRecordKind
                                )
                            )
                            ( HsProtobuf.encodeMessageField
                                (HsProtobuf.FieldNumber 7)
                                memoryRecordImportance
                            )
                        )
                        ( HsProtobuf.encodeMessageField
                            (HsProtobuf.FieldNumber 8)
                            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                                memoryRecordSummary
                            )
                        )
                    )
                    ( HsProtobuf.encodeMessageField
                        (HsProtobuf.FieldNumber 9)
                        ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                            memoryRecordDetail
                        )
                    )
                )
                ( HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 10)
                    memoryRecordCreatedAt
                )
            )
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 11)
                memoryRecordSupersedesId
            )
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 12)
            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                memoryRecordMetadataJson
            )
        )
  decodeMessage _ =
    Hs.pure MemoryRecord
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 1)
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 3)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 4)
              )
          )
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 5)
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 6)
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 7)
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 8)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 9)
              )
          )
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 10)
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 11)
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 12)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.Int64)
        (HsProtobufAST.Single "id")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "run_id")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 3)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "agent_id")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 4)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "birth_branch")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 5)
        (HsProtobufAST.Prim HsProtobufAST.Int64)
        (HsProtobufAST.Single "issue_id")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 6)
        ( HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "MemoryKind"))
        )
        (HsProtobufAST.Single "kind")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 7)
        (HsProtobufAST.Prim HsProtobufAST.Int32)
        (HsProtobufAST.Single "importance")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 8)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "summary")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 9)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "detail")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 10)
        (HsProtobufAST.Prim HsProtobufAST.Int64)
        (HsProtobufAST.Single "created_at")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 11)
        (HsProtobufAST.Prim HsProtobufAST.Int64)
        (HsProtobufAST.Single "supersedes_id")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 12)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "metadata_json")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB MemoryRecord) where
  toJSONPB (MemoryRecord f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12) =
    HsJSONPB.object
      [ "id" .= f1,
        "run_id" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "agent_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
        "birth_branch"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4),
        "issue_id" .= f5,
        "kind" .= f6,
        "importance" .= f7,
        "summary"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f8),
        "detail" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f9),
        "created_at" .= f10,
        "supersedes_id" .= f11,
        "metadata_json"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f12)
      ]
  toEncodingPB (MemoryRecord f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12) =
    HsJSONPB.pairs
      [ "id" .= f1,
        "run_id" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "agent_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
        "birth_branch"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4),
        "issue_id" .= f5,
        "kind" .= f6,
        "importance" .= f7,
        "summary"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f8),
        "detail" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f9),
        "created_at" .= f10,
        "supersedes_id" .= f11,
        "metadata_json"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f12)
      ]

instance (HsJSONPB.FromJSONPB MemoryRecord) where
  parseJSONPB =
    HsJSONPB.withObject
      "MemoryRecord"
      ( \obj ->
          Hs.pure MemoryRecord
            <*> obj .: "id"
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "run_id")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "agent_id")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "birth_branch")
                )
            <*> obj .: "issue_id"
            <*> obj .: "kind"
            <*> obj .: "importance"
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "summary")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "detail")
                )
            <*> obj .: "created_at"
            <*> obj .: "supersedes_id"
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "metadata_json")
                )
      )

instance (HsJSONPB.ToJSON MemoryRecord) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON MemoryRecord) where
  parseJSON = HsJSONPB.parseJSONPB

data MemoryAppendRequest
  = MemoryAppendRequest
  { memoryAppendRequestRunId :: Hs.Text,
    memoryAppendRequestAgentId :: Hs.Text,
    memoryAppendRequestBirthBranch :: Hs.Text,
    memoryAppendRequestIssueId :: Hs.Int64,
    memoryAppendRequestKind :: (HsProtobuf.Enumerated Effects.Memory.MemoryKind),
    memoryAppendRequestImportance :: Hs.Int32,
    memoryAppendRequestSummary :: Hs.Text,
    memoryAppendRequestDetail :: Hs.Text,
    memoryAppendRequestSupersedesId :: Hs.Int64,
    memoryAppendRequestMetadataJson :: Hs.Text
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData MemoryAppendRequest)

instance (HsProtobuf.Named MemoryAppendRequest) where
  nameOf _ = Hs.fromString "MemoryAppendRequest"

instance (HsProtobuf.HasDefault MemoryAppendRequest)

instance (HsProtobuf.Message MemoryAppendRequest) where
  encodeMessage
    _
    MemoryAppendRequest
      { memoryAppendRequestRunId,
        memoryAppendRequestAgentId,
        memoryAppendRequestBirthBranch,
        memoryAppendRequestIssueId,
        memoryAppendRequestKind,
        memoryAppendRequestImportance,
        memoryAppendRequestSummary,
        memoryAppendRequestDetail,
        memoryAppendRequestSupersedesId,
        memoryAppendRequestMetadataJson
      } =
      Hs.mappend
        ( Hs.mappend
            ( Hs.mappend
                ( Hs.mappend
                    ( Hs.mappend
                        ( Hs.mappend
                            ( Hs.mappend
                                ( Hs.mappend
                                    ( Hs.mappend
                                        ( HsProtobuf.encodeMessageField
                                            (HsProtobuf.FieldNumber 1)
                                            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                                                memoryAppendRequestRunId
                                            )
                                        )
                                        ( HsProtobuf.encodeMessageField
                                            (HsProtobuf.FieldNumber 2)
                                            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                                                memoryAppendRequestAgentId
                                            )
                                        )
                                    )
                                    ( HsProtobuf.encodeMessageField
                                        (HsProtobuf.FieldNumber 3)
                                        ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                                            memoryAppendRequestBirthBranch
                                        )
                                    )
                                )
                                ( HsProtobuf.encodeMessageField
                                    (HsProtobuf.FieldNumber 4)
                                    memoryAppendRequestIssueId
                                )
                            )
                            ( HsProtobuf.encodeMessageField
                                (HsProtobuf.FieldNumber 5)
                                memoryAppendRequestKind
                            )
                        )
                        ( HsProtobuf.encodeMessageField
                            (HsProtobuf.FieldNumber 6)
                            memoryAppendRequestImportance
                        )
                    )
                    ( HsProtobuf.encodeMessageField
                        (HsProtobuf.FieldNumber 7)
                        ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                            memoryAppendRequestSummary
                        )
                    )
                )
                ( HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 8)
                    ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                        memoryAppendRequestDetail
                    )
                )
            )
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 9)
                memoryAppendRequestSupersedesId
            )
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 10)
            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                memoryAppendRequestMetadataJson
            )
        )
  decodeMessage _ =
    Hs.pure MemoryAppendRequest
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 3)
              )
          )
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 4)
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 5)
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 6)
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 7)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 8)
              )
          )
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 9)
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 10)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "run_id")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "agent_id")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 3)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "birth_branch")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 4)
        (HsProtobufAST.Prim HsProtobufAST.Int64)
        (HsProtobufAST.Single "issue_id")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 5)
        ( HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "MemoryKind"))
        )
        (HsProtobufAST.Single "kind")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 6)
        (HsProtobufAST.Prim HsProtobufAST.Int32)
        (HsProtobufAST.Single "importance")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 7)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "summary")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 8)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "detail")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 9)
        (HsProtobufAST.Prim HsProtobufAST.Int64)
        (HsProtobufAST.Single "supersedes_id")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 10)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "metadata_json")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB MemoryAppendRequest) where
  toJSONPB (MemoryAppendRequest f1 f2 f3 f4 f5 f6 f7 f8 f9 f10) =
    HsJSONPB.object
      [ "run_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "agent_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "birth_branch"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
        "issue_id" .= f4,
        "kind" .= f5,
        "importance" .= f6,
        "summary"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f7),
        "detail" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f8),
        "supersedes_id" .= f9,
        "metadata_json"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f10)
      ]
  toEncodingPB (MemoryAppendRequest f1 f2 f3 f4 f5 f6 f7 f8 f9 f10) =
    HsJSONPB.pairs
      [ "run_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "agent_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "birth_branch"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
        "issue_id" .= f4,
        "kind" .= f5,
        "importance" .= f6,
        "summary"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f7),
        "detail" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f8),
        "supersedes_id" .= f9,
        "metadata_json"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f10)
      ]

instance (HsJSONPB.FromJSONPB MemoryAppendRequest) where
  parseJSONPB =
    HsJSONPB.withObject
      "MemoryAppendRequest"
      ( \obj ->
          Hs.pure MemoryAppendRequest
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "run_id")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "agent_id")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "birth_branch")
                )
            <*> obj .: "issue_id"
            <*> obj .: "kind"
            <*> obj .: "importance"
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "summary")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "detail")
                )
            <*> obj .: "supersedes_id"
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "metadata_json")
                )
      )

instance (HsJSONPB.ToJSON MemoryAppendRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON MemoryAppendRequest) where
  parseJSON = HsJSONPB.parseJSONPB

newtype MemoryAppendResponse
  = MemoryAppendResponse {memoryAppendResponseId :: Hs.Int64}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData MemoryAppendResponse)

instance (HsProtobuf.Named MemoryAppendResponse) where
  nameOf _ = Hs.fromString "MemoryAppendResponse"

instance (HsProtobuf.HasDefault MemoryAppendResponse)

instance (HsProtobuf.Message MemoryAppendResponse) where
  encodeMessage _ MemoryAppendResponse {memoryAppendResponseId} =
    ( HsProtobuf.encodeMessageField
        (HsProtobuf.FieldNumber 1)
        memoryAppendResponseId
    )
  decodeMessage _ =
    Hs.pure MemoryAppendResponse
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 1)
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.Int64)
        (HsProtobufAST.Single "id")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB MemoryAppendResponse) where
  toJSONPB (MemoryAppendResponse f1) = HsJSONPB.object ["id" .= f1]
  toEncodingPB (MemoryAppendResponse f1) =
    HsJSONPB.pairs ["id" .= f1]

instance (HsJSONPB.FromJSONPB MemoryAppendResponse) where
  parseJSONPB =
    HsJSONPB.withObject
      "MemoryAppendResponse"
      (\obj -> Hs.pure MemoryAppendResponse <*> obj .: "id")

instance (HsJSONPB.ToJSON MemoryAppendResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON MemoryAppendResponse) where
  parseJSON = HsJSONPB.parseJSONPB

data MemoryListRequest
  = MemoryListRequest
  { memoryListRequestRunId :: Hs.Text,
    memoryListRequestAgentId :: Hs.Text,
    memoryListRequestIssueId :: Hs.Int64,
    memoryListRequestKind :: (HsProtobuf.Enumerated Effects.Memory.MemoryKind),
    memoryListRequestMinImportance :: Hs.Int32,
    memoryListRequestLimit :: Hs.Int32
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData MemoryListRequest)

instance (HsProtobuf.Named MemoryListRequest) where
  nameOf _ = Hs.fromString "MemoryListRequest"

instance (HsProtobuf.HasDefault MemoryListRequest)

instance (HsProtobuf.Message MemoryListRequest) where
  encodeMessage
    _
    MemoryListRequest
      { memoryListRequestRunId,
        memoryListRequestAgentId,
        memoryListRequestIssueId,
        memoryListRequestKind,
        memoryListRequestMinImportance,
        memoryListRequestLimit
      } =
      Hs.mappend
        ( Hs.mappend
            ( Hs.mappend
                ( Hs.mappend
                    ( Hs.mappend
                        ( HsProtobuf.encodeMessageField
                            (HsProtobuf.FieldNumber 1)
                            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                                memoryListRequestRunId
                            )
                        )
                        ( HsProtobuf.encodeMessageField
                            (HsProtobuf.FieldNumber 2)
                            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                                memoryListRequestAgentId
                            )
                        )
                    )
                    ( HsProtobuf.encodeMessageField
                        (HsProtobuf.FieldNumber 3)
                        memoryListRequestIssueId
                    )
                )
                ( HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 4)
                    memoryListRequestKind
                )
            )
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 5)
                memoryListRequestMinImportance
            )
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 6)
            memoryListRequestLimit
        )
  decodeMessage _ =
    Hs.pure MemoryListRequest
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 3)
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 4)
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 5)
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 6)
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "run_id")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "agent_id")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 3)
        (HsProtobufAST.Prim HsProtobufAST.Int64)
        (HsProtobufAST.Single "issue_id")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 4)
        ( HsProtobufAST.Prim
            (HsProtobufAST.Named (HsProtobufAST.Single "MemoryKind"))
        )
        (HsProtobufAST.Single "kind")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 5)
        (HsProtobufAST.Prim HsProtobufAST.Int32)
        (HsProtobufAST.Single "min_importance")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 6)
        (HsProtobufAST.Prim HsProtobufAST.Int32)
        (HsProtobufAST.Single "limit")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB MemoryListRequest) where
  toJSONPB (MemoryListRequest f1 f2 f3 f4 f5 f6) =
    HsJSONPB.object
      [ "run_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "agent_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "issue_id" .= f3,
        "kind" .= f4,
        "min_importance" .= f5,
        "limit" .= f6
      ]
  toEncodingPB (MemoryListRequest f1 f2 f3 f4 f5 f6) =
    HsJSONPB.pairs
      [ "run_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "agent_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "issue_id" .= f3,
        "kind" .= f4,
        "min_importance" .= f5,
        "limit" .= f6
      ]

instance (HsJSONPB.FromJSONPB MemoryListRequest) where
  parseJSONPB =
    HsJSONPB.withObject
      "MemoryListRequest"
      ( \obj ->
          Hs.pure MemoryListRequest
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "run_id")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "agent_id")
                )
            <*> obj .: "issue_id"
            <*> obj .: "kind"
            <*> obj .: "min_importance"
            <*> obj .: "limit"
      )

instance (HsJSONPB.ToJSON MemoryListRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON MemoryListRequest) where
  parseJSON = HsJSONPB.parseJSONPB

newtype MemoryListResponse
  = MemoryListResponse {memoryListResponseRecords :: (Hs.Vector Effects.Memory.MemoryRecord)}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData MemoryListResponse)

instance (HsProtobuf.Named MemoryListResponse) where
  nameOf _ = Hs.fromString "MemoryListResponse"

instance (HsProtobuf.HasDefault MemoryListResponse)

instance (HsProtobuf.Message MemoryListResponse) where
  encodeMessage _ MemoryListResponse {memoryListResponseRecords} =
    ( HsProtobuf.encodeMessageField
        (HsProtobuf.FieldNumber 1)
        ( ( Hs.coerce
              @(Hs.Vector Effects.Memory.MemoryRecord)
              @(HsProtobuf.NestedVec Effects.Memory.MemoryRecord)
          )
            memoryListResponseRecords
        )
    )
  decodeMessage _ =
    Hs.pure MemoryListResponse
      <*> ( ( HsProtobuf.coerceOver
                @(HsProtobuf.NestedVec Effects.Memory.MemoryRecord)
                @(Hs.Vector Effects.Memory.MemoryRecord)
            )
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        ( HsProtobufAST.Repeated
            (HsProtobufAST.Named (HsProtobufAST.Single "MemoryRecord"))
        )
        (HsProtobufAST.Single "records")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB MemoryListResponse) where
  toJSONPB (MemoryListResponse f1) =
    HsJSONPB.object
      [ "records"
          .= ( ( Hs.coerce
                   @(Hs.Vector Effects.Memory.MemoryRecord)
                   @(HsProtobuf.NestedVec Effects.Memory.MemoryRecord)
               )
                 f1
             )
      ]
  toEncodingPB (MemoryListResponse f1) =
    HsJSONPB.pairs
      [ "records"
          .= ( ( Hs.coerce
                   @(Hs.Vector Effects.Memory.MemoryRecord)
                   @(HsProtobuf.NestedVec Effects.Memory.MemoryRecord)
               )
                 f1
             )
      ]

instance (HsJSONPB.FromJSONPB MemoryListResponse) where
  parseJSONPB =
    HsJSONPB.withObject
      "MemoryListResponse"
      ( \obj ->
          Hs.pure MemoryListResponse
            <*> ( ( HsProtobuf.coerceOver
                      @(HsProtobuf.NestedVec Effects.Memory.MemoryRecord)
                      @(Hs.Vector Effects.Memory.MemoryRecord)
                  )
                    (obj .: "records")
                )
      )

instance (HsJSONPB.ToJSON MemoryListResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON MemoryListResponse) where
  parseJSON = HsJSONPB.parseJSONPB
