{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE NegativeLiterals #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
{-# OPTIONS_GHC -fno-warn-missing-export-lists #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-- | Generated by Haskell protocol buffer compiler. DO NOT EDIT!
module Effects.Session where

import Control.Applicative ((<$>), (<*>), (<|>))
import Control.Applicative qualified as Hs
import Control.DeepSeq qualified as Hs
import Control.Monad qualified as Hs
import Data.ByteString qualified as Hs
import Data.Coerce qualified as Hs
import Data.Int qualified as Hs (Int16, Int32, Int64)
import Data.List.NonEmpty qualified as Hs (NonEmpty (..))
import Data.Map qualified as Hs (Map, mapKeysMonotonic)
import Data.Proxy qualified as Proxy
import Data.String qualified as Hs (fromString)
import Data.Text.Lazy qualified as Hs (Text)
import Data.Vector qualified as Hs (Vector)
import Data.Word qualified as Hs (Word16, Word32, Word64)
import GHC.Enum qualified as Hs
import GHC.Generics qualified as Hs
import Google.Protobuf.Wrappers.Polymorphic qualified as HsProtobuf
  ( Wrapped (..),
  )
import Proto3.Suite.Class qualified as HsProtobuf
import Proto3.Suite.DotProto qualified as HsProtobufAST
import Proto3.Suite.JSONPB ((.:), (.=))
import Proto3.Suite.JSONPB qualified as HsJSONPB
import Proto3.Suite.Types qualified as HsProtobuf
import Proto3.Wire qualified as HsProtobuf
import Proto3.Wire.Decode qualified as HsProtobuf
  ( Parser,
    RawField,
  )
import Unsafe.Coerce qualified as Hs
import Prelude qualified as Hs

newtype RegisterClaudeSessionRequest
  = RegisterClaudeSessionRequest {registerClaudeSessionRequestClaudeSessionId :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData RegisterClaudeSessionRequest)

instance (HsProtobuf.Named RegisterClaudeSessionRequest) where
  nameOf _ = Hs.fromString "RegisterClaudeSessionRequest"

instance (HsProtobuf.HasDefault RegisterClaudeSessionRequest)

instance (HsProtobuf.Message RegisterClaudeSessionRequest) where
  encodeMessage
    _
    RegisterClaudeSessionRequest {registerClaudeSessionRequestClaudeSessionId} =
      ( HsProtobuf.encodeMessageField
          (HsProtobuf.FieldNumber 1)
          ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
              registerClaudeSessionRequestClaudeSessionId
          )
      )
  decodeMessage _ =
    Hs.pure RegisterClaudeSessionRequest
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "claude_session_id")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB RegisterClaudeSessionRequest) where
  toJSONPB (RegisterClaudeSessionRequest f1) =
    HsJSONPB.object
      [ "claude_session_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)
      ]
  toEncodingPB (RegisterClaudeSessionRequest f1) =
    HsJSONPB.pairs
      [ "claude_session_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)
      ]

instance (HsJSONPB.FromJSONPB RegisterClaudeSessionRequest) where
  parseJSONPB =
    HsJSONPB.withObject
      "RegisterClaudeSessionRequest"
      ( \obj ->
          Hs.pure RegisterClaudeSessionRequest
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "claude_session_id")
                )
      )

instance (HsJSONPB.ToJSON RegisterClaudeSessionRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON RegisterClaudeSessionRequest) where
  parseJSON = HsJSONPB.parseJSONPB

newtype RegisterClaudeSessionResponse
  = RegisterClaudeSessionResponse {registerClaudeSessionResponseSuccess :: Hs.Bool}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData RegisterClaudeSessionResponse)

instance (HsProtobuf.Named RegisterClaudeSessionResponse) where
  nameOf _ = Hs.fromString "RegisterClaudeSessionResponse"

instance (HsProtobuf.HasDefault RegisterClaudeSessionResponse)

instance (HsProtobuf.Message RegisterClaudeSessionResponse) where
  encodeMessage
    _
    RegisterClaudeSessionResponse {registerClaudeSessionResponseSuccess} =
      ( HsProtobuf.encodeMessageField
          (HsProtobuf.FieldNumber 1)
          registerClaudeSessionResponseSuccess
      )
  decodeMessage _ =
    Hs.pure RegisterClaudeSessionResponse
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 1)
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.Bool)
        (HsProtobufAST.Single "success")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB RegisterClaudeSessionResponse) where
  toJSONPB (RegisterClaudeSessionResponse f1) =
    HsJSONPB.object ["success" .= f1]
  toEncodingPB (RegisterClaudeSessionResponse f1) =
    HsJSONPB.pairs ["success" .= f1]

instance (HsJSONPB.FromJSONPB RegisterClaudeSessionResponse) where
  parseJSONPB =
    HsJSONPB.withObject
      "RegisterClaudeSessionResponse"
      ( \obj ->
          Hs.pure RegisterClaudeSessionResponse <*> obj .: "success"
      )

instance (HsJSONPB.ToJSON RegisterClaudeSessionResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON RegisterClaudeSessionResponse) where
  parseJSON = HsJSONPB.parseJSONPB

data RegisterTeamRequest
  = RegisterTeamRequest
  { registerTeamRequestTeamName :: Hs.Text,
    registerTeamRequestInboxName :: Hs.Text
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData RegisterTeamRequest)

instance (HsProtobuf.Named RegisterTeamRequest) where
  nameOf _ = Hs.fromString "RegisterTeamRequest"

instance (HsProtobuf.HasDefault RegisterTeamRequest)

instance (HsProtobuf.Message RegisterTeamRequest) where
  encodeMessage
    _
    RegisterTeamRequest
      { registerTeamRequestTeamName,
        registerTeamRequestInboxName
      } =
      Hs.mappend
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 1)
            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                registerTeamRequestTeamName
            )
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 2)
            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                registerTeamRequestInboxName
            )
        )
  decodeMessage _ =
    Hs.pure RegisterTeamRequest
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "team_name")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "inbox_name")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB RegisterTeamRequest) where
  toJSONPB (RegisterTeamRequest f1 f2) =
    HsJSONPB.object
      [ "team_name"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "inbox_name"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)
      ]
  toEncodingPB (RegisterTeamRequest f1 f2) =
    HsJSONPB.pairs
      [ "team_name"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "inbox_name"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2)
      ]

instance (HsJSONPB.FromJSONPB RegisterTeamRequest) where
  parseJSONPB =
    HsJSONPB.withObject
      "RegisterTeamRequest"
      ( \obj ->
          Hs.pure RegisterTeamRequest
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "team_name")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "inbox_name")
                )
      )

instance (HsJSONPB.ToJSON RegisterTeamRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON RegisterTeamRequest) where
  parseJSON = HsJSONPB.parseJSONPB

newtype RegisterTeamResponse
  = RegisterTeamResponse {registerTeamResponseSuccess :: Hs.Bool}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData RegisterTeamResponse)

instance (HsProtobuf.Named RegisterTeamResponse) where
  nameOf _ = Hs.fromString "RegisterTeamResponse"

instance (HsProtobuf.HasDefault RegisterTeamResponse)

instance (HsProtobuf.Message RegisterTeamResponse) where
  encodeMessage _ RegisterTeamResponse {registerTeamResponseSuccess} =
    ( HsProtobuf.encodeMessageField
        (HsProtobuf.FieldNumber 1)
        registerTeamResponseSuccess
    )
  decodeMessage _ =
    Hs.pure RegisterTeamResponse
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 1)
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.Bool)
        (HsProtobufAST.Single "success")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB RegisterTeamResponse) where
  toJSONPB (RegisterTeamResponse f1) =
    HsJSONPB.object ["success" .= f1]
  toEncodingPB (RegisterTeamResponse f1) =
    HsJSONPB.pairs ["success" .= f1]

instance (HsJSONPB.FromJSONPB RegisterTeamResponse) where
  parseJSONPB =
    HsJSONPB.withObject
      "RegisterTeamResponse"
      (\obj -> Hs.pure RegisterTeamResponse <*> obj .: "success")

instance (HsJSONPB.ToJSON RegisterTeamResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON RegisterTeamResponse) where
  parseJSON = HsJSONPB.parseJSONPB

data DeregisterTeamRequest
  = DeregisterTeamRequest {}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData DeregisterTeamRequest)

instance (HsProtobuf.Named DeregisterTeamRequest) where
  nameOf _ = Hs.fromString "DeregisterTeamRequest"

instance (HsProtobuf.HasDefault DeregisterTeamRequest)

instance (HsProtobuf.Message DeregisterTeamRequest) where
  encodeMessage _ DeregisterTeamRequest {} = Hs.mempty
  decodeMessage _ = Hs.pure DeregisterTeamRequest
  dotProto _ = []

instance (HsJSONPB.ToJSONPB DeregisterTeamRequest) where
  toJSONPB DeregisterTeamRequest = HsJSONPB.object []
  toEncodingPB DeregisterTeamRequest = HsJSONPB.pairs []

instance (HsJSONPB.FromJSONPB DeregisterTeamRequest) where
  parseJSONPB =
    HsJSONPB.withObject
      "DeregisterTeamRequest"
      (\obj -> Hs.pure DeregisterTeamRequest)

instance (HsJSONPB.ToJSON DeregisterTeamRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON DeregisterTeamRequest) where
  parseJSON = HsJSONPB.parseJSONPB

newtype DeregisterTeamResponse
  = DeregisterTeamResponse {deregisterTeamResponseSuccess :: Hs.Bool}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData DeregisterTeamResponse)

instance (HsProtobuf.Named DeregisterTeamResponse) where
  nameOf _ = Hs.fromString "DeregisterTeamResponse"

instance (HsProtobuf.HasDefault DeregisterTeamResponse)

instance (HsProtobuf.Message DeregisterTeamResponse) where
  encodeMessage
    _
    DeregisterTeamResponse {deregisterTeamResponseSuccess} =
      ( HsProtobuf.encodeMessageField
          (HsProtobuf.FieldNumber 1)
          deregisterTeamResponseSuccess
      )
  decodeMessage _ =
    Hs.pure DeregisterTeamResponse
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 1)
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.Bool)
        (HsProtobufAST.Single "success")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB DeregisterTeamResponse) where
  toJSONPB (DeregisterTeamResponse f1) =
    HsJSONPB.object ["success" .= f1]
  toEncodingPB (DeregisterTeamResponse f1) =
    HsJSONPB.pairs ["success" .= f1]

instance (HsJSONPB.FromJSONPB DeregisterTeamResponse) where
  parseJSONPB =
    HsJSONPB.withObject
      "DeregisterTeamResponse"
      (\obj -> Hs.pure DeregisterTeamResponse <*> obj .: "success")

instance (HsJSONPB.ToJSON DeregisterTeamResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON DeregisterTeamResponse) where
  parseJSON = HsJSONPB.parseJSONPB

data RegisterSupervisorRequest
  = RegisterSupervisorRequest
  { registerSupervisorRequestChildren :: (Hs.Vector Hs.Text),
    registerSupervisorRequestSupervisor :: Hs.Text,
    registerSupervisorRequestTeam :: Hs.Text
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData RegisterSupervisorRequest)

instance (HsProtobuf.Named RegisterSupervisorRequest) where
  nameOf _ = Hs.fromString "RegisterSupervisorRequest"

instance (HsProtobuf.HasDefault RegisterSupervisorRequest)

instance (HsProtobuf.Message RegisterSupervisorRequest) where
  encodeMessage
    _
    RegisterSupervisorRequest
      { registerSupervisorRequestChildren,
        registerSupervisorRequestSupervisor,
        registerSupervisorRequestTeam
      } =
      Hs.mappend
        ( Hs.mappend
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 1)
                ( ( Hs.coerce
                      @(Hs.Vector Hs.Text)
                      @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
                  )
                    registerSupervisorRequestChildren
                )
            )
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 2)
                ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                    registerSupervisorRequestSupervisor
                )
            )
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 3)
            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                registerSupervisorRequestTeam
            )
        )
  decodeMessage _ =
    Hs.pure RegisterSupervisorRequest
      <*> ( ( HsProtobuf.coerceOver
                @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
                @(Hs.Vector Hs.Text)
            )
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 3)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Repeated HsProtobufAST.String)
        (HsProtobufAST.Single "children")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "supervisor")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 3)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "team")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB RegisterSupervisorRequest) where
  toJSONPB (RegisterSupervisorRequest f1 f2 f3) =
    HsJSONPB.object
      [ "children"
          .= ( ( Hs.coerce
                   @(Hs.Vector Hs.Text)
                   @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
               )
                 f1
             ),
        "supervisor"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "team" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)
      ]
  toEncodingPB (RegisterSupervisorRequest f1 f2 f3) =
    HsJSONPB.pairs
      [ "children"
          .= ( ( Hs.coerce
                   @(Hs.Vector Hs.Text)
                   @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
               )
                 f1
             ),
        "supervisor"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "team" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3)
      ]

instance (HsJSONPB.FromJSONPB RegisterSupervisorRequest) where
  parseJSONPB =
    HsJSONPB.withObject
      "RegisterSupervisorRequest"
      ( \obj ->
          Hs.pure RegisterSupervisorRequest
            <*> ( ( HsProtobuf.coerceOver
                      @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
                      @(Hs.Vector Hs.Text)
                  )
                    (obj .: "children")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "supervisor")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "team")
                )
      )

instance (HsJSONPB.ToJSON RegisterSupervisorRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON RegisterSupervisorRequest) where
  parseJSON = HsJSONPB.parseJSONPB

data RegisterSupervisorResponse
  = RegisterSupervisorResponse
  { registerSupervisorResponseSuccess :: Hs.Bool,
    registerSupervisorResponseRegisteredCount :: Hs.Int32
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData RegisterSupervisorResponse)

instance (HsProtobuf.Named RegisterSupervisorResponse) where
  nameOf _ = Hs.fromString "RegisterSupervisorResponse"

instance (HsProtobuf.HasDefault RegisterSupervisorResponse)

instance (HsProtobuf.Message RegisterSupervisorResponse) where
  encodeMessage
    _
    RegisterSupervisorResponse
      { registerSupervisorResponseSuccess,
        registerSupervisorResponseRegisteredCount
      } =
      Hs.mappend
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 1)
            registerSupervisorResponseSuccess
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 2)
            registerSupervisorResponseRegisteredCount
        )
  decodeMessage _ =
    Hs.pure RegisterSupervisorResponse
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 1)
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 2)
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.Bool)
        (HsProtobufAST.Single "success")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.Int32)
        (HsProtobufAST.Single "registered_count")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB RegisterSupervisorResponse) where
  toJSONPB (RegisterSupervisorResponse f1 f2) =
    HsJSONPB.object ["success" .= f1, "registered_count" .= f2]
  toEncodingPB (RegisterSupervisorResponse f1 f2) =
    HsJSONPB.pairs ["success" .= f1, "registered_count" .= f2]

instance (HsJSONPB.FromJSONPB RegisterSupervisorResponse) where
  parseJSONPB =
    HsJSONPB.withObject
      "RegisterSupervisorResponse"
      ( \obj ->
          Hs.pure RegisterSupervisorResponse
            <*> obj .: "success"
            <*> obj .: "registered_count"
      )

instance (HsJSONPB.ToJSON RegisterSupervisorResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON RegisterSupervisorResponse) where
  parseJSON = HsJSONPB.parseJSONPB

newtype DeregisterSupervisorRequest
  = DeregisterSupervisorRequest {deregisterSupervisorRequestChildren :: (Hs.Vector Hs.Text)}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData DeregisterSupervisorRequest)

instance (HsProtobuf.Named DeregisterSupervisorRequest) where
  nameOf _ = Hs.fromString "DeregisterSupervisorRequest"

instance (HsProtobuf.HasDefault DeregisterSupervisorRequest)

instance (HsProtobuf.Message DeregisterSupervisorRequest) where
  encodeMessage
    _
    DeregisterSupervisorRequest {deregisterSupervisorRequestChildren} =
      ( HsProtobuf.encodeMessageField
          (HsProtobuf.FieldNumber 1)
          ( ( Hs.coerce
                @(Hs.Vector Hs.Text)
                @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
            )
              deregisterSupervisorRequestChildren
          )
      )
  decodeMessage _ =
    Hs.pure DeregisterSupervisorRequest
      <*> ( ( HsProtobuf.coerceOver
                @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
                @(Hs.Vector Hs.Text)
            )
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Repeated HsProtobufAST.String)
        (HsProtobufAST.Single "children")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB DeregisterSupervisorRequest) where
  toJSONPB (DeregisterSupervisorRequest f1) =
    HsJSONPB.object
      [ "children"
          .= ( ( Hs.coerce
                   @(Hs.Vector Hs.Text)
                   @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
               )
                 f1
             )
      ]
  toEncodingPB (DeregisterSupervisorRequest f1) =
    HsJSONPB.pairs
      [ "children"
          .= ( ( Hs.coerce
                   @(Hs.Vector Hs.Text)
                   @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
               )
                 f1
             )
      ]

instance (HsJSONPB.FromJSONPB DeregisterSupervisorRequest) where
  parseJSONPB =
    HsJSONPB.withObject
      "DeregisterSupervisorRequest"
      ( \obj ->
          Hs.pure DeregisterSupervisorRequest
            <*> ( ( HsProtobuf.coerceOver
                      @(HsProtobuf.UnpackedVec (HsProtobuf.String Hs.Text))
                      @(Hs.Vector Hs.Text)
                  )
                    (obj .: "children")
                )
      )

instance (HsJSONPB.ToJSON DeregisterSupervisorRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON DeregisterSupervisorRequest) where
  parseJSON = HsJSONPB.parseJSONPB

newtype DeregisterSupervisorResponse
  = DeregisterSupervisorResponse {deregisterSupervisorResponseSuccess :: Hs.Bool}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData DeregisterSupervisorResponse)

instance (HsProtobuf.Named DeregisterSupervisorResponse) where
  nameOf _ = Hs.fromString "DeregisterSupervisorResponse"

instance (HsProtobuf.HasDefault DeregisterSupervisorResponse)

instance (HsProtobuf.Message DeregisterSupervisorResponse) where
  encodeMessage
    _
    DeregisterSupervisorResponse {deregisterSupervisorResponseSuccess} =
      ( HsProtobuf.encodeMessageField
          (HsProtobuf.FieldNumber 1)
          deregisterSupervisorResponseSuccess
      )
  decodeMessage _ =
    Hs.pure DeregisterSupervisorResponse
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 1)
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.Bool)
        (HsProtobufAST.Single "success")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB DeregisterSupervisorResponse) where
  toJSONPB (DeregisterSupervisorResponse f1) =
    HsJSONPB.object ["success" .= f1]
  toEncodingPB (DeregisterSupervisorResponse f1) =
    HsJSONPB.pairs ["success" .= f1]

instance (HsJSONPB.FromJSONPB DeregisterSupervisorResponse) where
  parseJSONPB =
    HsJSONPB.withObject
      "DeregisterSupervisorResponse"
      ( \obj ->
          Hs.pure DeregisterSupervisorResponse <*> obj .: "success"
      )

instance (HsJSONPB.ToJSON DeregisterSupervisorResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON DeregisterSupervisorResponse) where
  parseJSON = HsJSONPB.parseJSONPB

data AgentStatus
  = AgentStatus
  { agentStatusName :: Hs.Text,
    agentStatusRole :: Hs.Text,
    agentStatusIssue :: Hs.Text,
    agentStatusWindowId :: Hs.Text,
    agentStatusPaneId :: Hs.Text,
    agentStatusWindowAlive :: Hs.Bool,
    agentStatusAgeMins :: Hs.Word64,
    agentStatusBirthBranch :: Hs.Text
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData AgentStatus)

instance (HsProtobuf.Named AgentStatus) where
  nameOf _ = Hs.fromString "AgentStatus"

instance (HsProtobuf.HasDefault AgentStatus)

instance (HsProtobuf.Message AgentStatus) where
  encodeMessage
    _
    AgentStatus
      { agentStatusName,
        agentStatusRole,
        agentStatusIssue,
        agentStatusWindowId,
        agentStatusPaneId,
        agentStatusWindowAlive,
        agentStatusAgeMins,
        agentStatusBirthBranch
      } =
      Hs.mappend
        ( Hs.mappend
            ( Hs.mappend
                ( Hs.mappend
                    ( Hs.mappend
                        ( Hs.mappend
                            ( Hs.mappend
                                ( HsProtobuf.encodeMessageField
                                    (HsProtobuf.FieldNumber 1)
                                    ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                                        agentStatusName
                                    )
                                )
                                ( HsProtobuf.encodeMessageField
                                    (HsProtobuf.FieldNumber 2)
                                    ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                                        agentStatusRole
                                    )
                                )
                            )
                            ( HsProtobuf.encodeMessageField
                                (HsProtobuf.FieldNumber 3)
                                ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                                    agentStatusIssue
                                )
                            )
                        )
                        ( HsProtobuf.encodeMessageField
                            (HsProtobuf.FieldNumber 4)
                            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                                agentStatusWindowId
                            )
                        )
                    )
                    ( HsProtobuf.encodeMessageField
                        (HsProtobuf.FieldNumber 5)
                        ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                            agentStatusPaneId
                        )
                    )
                )
                ( HsProtobuf.encodeMessageField
                    (HsProtobuf.FieldNumber 6)
                    agentStatusWindowAlive
                )
            )
            ( HsProtobuf.encodeMessageField
                (HsProtobuf.FieldNumber 7)
                agentStatusAgeMins
            )
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 8)
            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                agentStatusBirthBranch
            )
        )
  decodeMessage _ =
    Hs.pure AgentStatus
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 3)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 4)
              )
          )
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 5)
              )
          )
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 6)
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 7)
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 8)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "name")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "role")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 3)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "issue")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 4)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "window_id")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 5)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "pane_id")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 6)
        (HsProtobufAST.Prim HsProtobufAST.Bool)
        (HsProtobufAST.Single "window_alive")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 7)
        (HsProtobufAST.Prim HsProtobufAST.UInt64)
        (HsProtobufAST.Single "age_mins")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 8)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "birth_branch")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB AgentStatus) where
  toJSONPB (AgentStatus f1 f2 f3 f4 f5 f6 f7 f8) =
    HsJSONPB.object
      [ "name" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "role" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "issue" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
        "window_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4),
        "pane_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f5),
        "window_alive" .= f6,
        "age_mins" .= f7,
        "birth_branch"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f8)
      ]
  toEncodingPB (AgentStatus f1 f2 f3 f4 f5 f6 f7 f8) =
    HsJSONPB.pairs
      [ "name" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "role" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f2),
        "issue" .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f3),
        "window_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f4),
        "pane_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f5),
        "window_alive" .= f6,
        "age_mins" .= f7,
        "birth_branch"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f8)
      ]

instance (HsJSONPB.FromJSONPB AgentStatus) where
  parseJSONPB =
    HsJSONPB.withObject
      "AgentStatus"
      ( \obj ->
          Hs.pure AgentStatus
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "name")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "role")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "issue")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "window_id")
                )
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "pane_id")
                )
            <*> obj .: "window_alive"
            <*> obj .: "age_mins"
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "birth_branch")
                )
      )

instance (HsJSONPB.ToJSON AgentStatus) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON AgentStatus) where
  parseJSON = HsJSONPB.parseJSONPB

newtype ListAgentsRequest
  = ListAgentsRequest {listAgentsRequestIncludeDead :: Hs.Bool}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData ListAgentsRequest)

instance (HsProtobuf.Named ListAgentsRequest) where
  nameOf _ = Hs.fromString "ListAgentsRequest"

instance (HsProtobuf.HasDefault ListAgentsRequest)

instance (HsProtobuf.Message ListAgentsRequest) where
  encodeMessage _ ListAgentsRequest {listAgentsRequestIncludeDead} =
    ( HsProtobuf.encodeMessageField
        (HsProtobuf.FieldNumber 1)
        listAgentsRequestIncludeDead
    )
  decodeMessage _ =
    Hs.pure ListAgentsRequest
      <*> HsProtobuf.at
        HsProtobuf.decodeMessageField
        (HsProtobuf.FieldNumber 1)
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.Bool)
        (HsProtobufAST.Single "include_dead")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB ListAgentsRequest) where
  toJSONPB (ListAgentsRequest f1) =
    HsJSONPB.object ["include_dead" .= f1]
  toEncodingPB (ListAgentsRequest f1) =
    HsJSONPB.pairs ["include_dead" .= f1]

instance (HsJSONPB.FromJSONPB ListAgentsRequest) where
  parseJSONPB =
    HsJSONPB.withObject
      "ListAgentsRequest"
      (\obj -> Hs.pure ListAgentsRequest <*> obj .: "include_dead")

instance (HsJSONPB.ToJSON ListAgentsRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON ListAgentsRequest) where
  parseJSON = HsJSONPB.parseJSONPB

newtype ListAgentsResponse
  = ListAgentsResponse {listAgentsResponseAgents :: (Hs.Vector Effects.Session.AgentStatus)}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData ListAgentsResponse)

instance (HsProtobuf.Named ListAgentsResponse) where
  nameOf _ = Hs.fromString "ListAgentsResponse"

instance (HsProtobuf.HasDefault ListAgentsResponse)

instance (HsProtobuf.Message ListAgentsResponse) where
  encodeMessage _ ListAgentsResponse {listAgentsResponseAgents} =
    ( HsProtobuf.encodeMessageField
        (HsProtobuf.FieldNumber 1)
        ( ( Hs.coerce
              @(Hs.Vector Effects.Session.AgentStatus)
              @(HsProtobuf.NestedVec Effects.Session.AgentStatus)
          )
            listAgentsResponseAgents
        )
    )
  decodeMessage _ =
    Hs.pure ListAgentsResponse
      <*> ( ( HsProtobuf.coerceOver
                @(HsProtobuf.NestedVec Effects.Session.AgentStatus)
                @(Hs.Vector Effects.Session.AgentStatus)
            )
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        ( HsProtobufAST.Repeated
            (HsProtobufAST.Named (HsProtobufAST.Single "AgentStatus"))
        )
        (HsProtobufAST.Single "agents")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB ListAgentsResponse) where
  toJSONPB (ListAgentsResponse f1) =
    HsJSONPB.object
      [ "agents"
          .= ( ( Hs.coerce
                   @(Hs.Vector Effects.Session.AgentStatus)
                   @(HsProtobuf.NestedVec Effects.Session.AgentStatus)
               )
                 f1
             )
      ]
  toEncodingPB (ListAgentsResponse f1) =
    HsJSONPB.pairs
      [ "agents"
          .= ( ( Hs.coerce
                   @(Hs.Vector Effects.Session.AgentStatus)
                   @(HsProtobuf.NestedVec Effects.Session.AgentStatus)
               )
                 f1
             )
      ]

instance (HsJSONPB.FromJSONPB ListAgentsResponse) where
  parseJSONPB =
    HsJSONPB.withObject
      "ListAgentsResponse"
      ( \obj ->
          Hs.pure ListAgentsResponse
            <*> ( ( HsProtobuf.coerceOver
                      @(HsProtobuf.NestedVec Effects.Session.AgentStatus)
                      @(Hs.Vector Effects.Session.AgentStatus)
                  )
                    (obj .: "agents")
                )
      )

instance (HsJSONPB.ToJSON ListAgentsResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON ListAgentsResponse) where
  parseJSON = HsJSONPB.parseJSONPB
