{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE NegativeLiterals #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
{-# OPTIONS_GHC -fno-warn-missing-export-lists #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-- | Generated by Haskell protocol buffer compiler. DO NOT EDIT!
module Effects.Tl where

import Control.Applicative ((<$>), (<*>), (<|>))
import Control.Applicative qualified as Hs
import Control.DeepSeq qualified as Hs
import Control.Monad qualified as Hs
import Data.ByteString qualified as Hs
import Data.Coerce qualified as Hs
import Data.Int qualified as Hs (Int16, Int32, Int64)
import Data.List.NonEmpty qualified as Hs (NonEmpty (..))
import Data.Map qualified as Hs (Map, mapKeysMonotonic)
import Data.Proxy qualified as Proxy
import Data.String qualified as Hs (fromString)
import Data.Text.Lazy qualified as Hs (Text)
import Data.Vector qualified as Hs (Vector)
import Data.Word qualified as Hs (Word16, Word32, Word64)
import GHC.Enum qualified as Hs
import GHC.Generics qualified as Hs
import Google.Protobuf.Wrappers.Polymorphic qualified as HsProtobuf
  ( Wrapped (..),
  )
import Proto3.Suite.Class qualified as HsProtobuf
import Proto3.Suite.DotProto qualified as HsProtobufAST
import Proto3.Suite.JSONPB ((.:), (.=))
import Proto3.Suite.JSONPB qualified as HsJSONPB
import Proto3.Suite.Types qualified as HsProtobuf
import Proto3.Wire qualified as HsProtobuf
import Proto3.Wire.Decode qualified as HsProtobuf
  ( Parser,
    RawField,
  )
import Unsafe.Coerce qualified as Hs
import Prelude qualified as Hs

data EmitEventRequest
  = EmitEventRequest
  { emitEventRequestEventType :: Hs.Text,
    emitEventRequestPayload :: Hs.ByteString
  }
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData EmitEventRequest)

instance (HsProtobuf.Named EmitEventRequest) where
  nameOf _ = Hs.fromString "EmitEventRequest"

instance (HsProtobuf.HasDefault EmitEventRequest)

instance (HsProtobuf.Message EmitEventRequest) where
  encodeMessage
    _
    EmitEventRequest
      { emitEventRequestEventType,
        emitEventRequestPayload
      } =
      Hs.mappend
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 1)
            ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
                emitEventRequestEventType
            )
        )
        ( HsProtobuf.encodeMessageField
            (HsProtobuf.FieldNumber 2)
            ( (Hs.coerce @Hs.ByteString @(HsProtobuf.Bytes Hs.ByteString))
                emitEventRequestPayload
            )
        )
  decodeMessage _ =
    Hs.pure EmitEventRequest
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
      <*> ( ( HsProtobuf.coerceOver
                @(HsProtobuf.Bytes Hs.ByteString)
                @Hs.ByteString
            )
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 2)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "event_type")
        []
        "",
      HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 2)
        (HsProtobufAST.Prim HsProtobufAST.Bytes)
        (HsProtobufAST.Single "payload")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB EmitEventRequest) where
  toJSONPB (EmitEventRequest f1 f2) =
    HsJSONPB.object
      [ "event_type"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "payload"
          .= ((Hs.coerce @Hs.ByteString @(HsProtobuf.Bytes Hs.ByteString)) f2)
      ]
  toEncodingPB (EmitEventRequest f1 f2) =
    HsJSONPB.pairs
      [ "event_type"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1),
        "payload"
          .= ((Hs.coerce @Hs.ByteString @(HsProtobuf.Bytes Hs.ByteString)) f2)
      ]

instance (HsJSONPB.FromJSONPB EmitEventRequest) where
  parseJSONPB =
    HsJSONPB.withObject
      "EmitEventRequest"
      ( \obj ->
          Hs.pure EmitEventRequest
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "event_type")
                )
            <*> ( ( HsProtobuf.coerceOver
                      @(HsProtobuf.Bytes Hs.ByteString)
                      @Hs.ByteString
                  )
                    (obj .: "payload")
                )
      )

instance (HsJSONPB.ToJSON EmitEventRequest) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON EmitEventRequest) where
  parseJSON = HsJSONPB.parseJSONPB

newtype EmitEventResponse
  = EmitEventResponse {emitEventResponseEventId :: Hs.Text}
  deriving (Hs.Show, Hs.Eq, Hs.Ord, Hs.Generic)

instance (Hs.NFData EmitEventResponse)

instance (HsProtobuf.Named EmitEventResponse) where
  nameOf _ = Hs.fromString "EmitEventResponse"

instance (HsProtobuf.HasDefault EmitEventResponse)

instance (HsProtobuf.Message EmitEventResponse) where
  encodeMessage _ EmitEventResponse {emitEventResponseEventId} =
    ( HsProtobuf.encodeMessageField
        (HsProtobuf.FieldNumber 1)
        ( (Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text))
            emitEventResponseEventId
        )
    )
  decodeMessage _ =
    Hs.pure EmitEventResponse
      <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
              ( HsProtobuf.at
                  HsProtobuf.decodeMessageField
                  (HsProtobuf.FieldNumber 1)
              )
          )
  dotProto _ =
    [ HsProtobufAST.DotProtoField
        (HsProtobuf.FieldNumber 1)
        (HsProtobufAST.Prim HsProtobufAST.String)
        (HsProtobufAST.Single "event_id")
        []
        ""
    ]

instance (HsJSONPB.ToJSONPB EmitEventResponse) where
  toJSONPB (EmitEventResponse f1) =
    HsJSONPB.object
      [ "event_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)
      ]
  toEncodingPB (EmitEventResponse f1) =
    HsJSONPB.pairs
      [ "event_id"
          .= ((Hs.coerce @Hs.Text @(HsProtobuf.String Hs.Text)) f1)
      ]

instance (HsJSONPB.FromJSONPB EmitEventResponse) where
  parseJSONPB =
    HsJSONPB.withObject
      "EmitEventResponse"
      ( \obj ->
          Hs.pure EmitEventResponse
            <*> ( (HsProtobuf.coerceOver @(HsProtobuf.String Hs.Text) @Hs.Text)
                    (obj .: "event_id")
                )
      )

instance (HsJSONPB.ToJSON EmitEventResponse) where
  toJSON = HsJSONPB.toAesonValue
  toEncoding = HsJSONPB.toAesonEncoding

instance (HsJSONPB.FromJSON EmitEventResponse) where
  parseJSON = HsJSONPB.parseJSONPB
