//! Tests for recognition and retirement of a stale ExoMonad-generated
//! project-root `.codex/config.toml`.
//!
//! The fixtures are generated by [`crate::codex_config::render_codex_config`],
//! so they are the shape older ExoMonad actually wrote rather than a hand-typed
//! approximation that could drift away from it unnoticed. The properties under
//! test are the ones the module promises: two independent ownership signals are
//! required, prose quoting a hook command is not evidence, a foreign
//! project-root config is never touched, the refusal names the file and the exact
//! `mv` that fixes it, retirement moves rather than deletes, and no backup is ever
//! overwritten.

use super::*;

use crate::codex_config::render_codex_config;
use std::collections::HashMap;

/// The `exomonad` binary path the historical fixture was rendered around.
const HISTORICAL_BINARY: &str = "/usr/local/bin/exomonad";

/// A project directory with a generated root config inside it.
fn project_with_generated_root(role: &str, agent_name: &str) -> tempfile::TempDir {
    let dir = tempfile::tempdir().expect("temp project");
    let config_path = dir.path().join(PROJECT_ROOT_CODEX_CONFIG);
    std::fs::create_dir_all(config_path.parent().unwrap()).unwrap();
    std::fs::write(&config_path, generated_root_config(role, agent_name)).unwrap();
    dir
}

/// The project-root Codex config older ExoMonad wrote for a Codex root agent.
fn generated_root_config(role: &str, agent_name: &str) -> String {
    render_codex_config(
        agent_name,
        role,
        "# Root TL protocol\n\nRetired root protocol text.",
        None,
        &HashMap::new(),
        Path::new(HISTORICAL_BINARY),
        Path::new("/tmp/exomonad-stale-root-project"),
    )
}

/// Write `contents` at the project root's Codex config path.
fn write_project_root_config(dir: &Path, contents: &str) {
    let config_path = dir.join(PROJECT_ROOT_CODEX_CONFIG);
    std::fs::create_dir_all(config_path.parent().unwrap()).unwrap();
    std::fs::write(config_path, contents).unwrap();
}

/// The operator-facing refusal, with the whole anyhow context chain flattened.
fn refusal_from(error: anyhow::Error) -> String {
    format!("{error:#}")
}

#[test]
fn recognizes_a_generated_project_root_config_for_a_retired_root_role() {
    for role in ["tl", "root"] {
        let dir = project_with_generated_root(role, "root");
        let stale = detect(dir.path())
            .unwrap()
            .unwrap_or_else(|| panic!("role {role} root config was not recognized"));

        assert_eq!(stale.role, role);
        assert_eq!(stale.agent_name, "root");
        assert_eq!(stale.hook_commands.len(), 3, "role {role}");
        assert!(
            stale
                .hook_commands
                .iter()
                .all(|command| command.contains("--runtime codex")),
            "role {role}: {:?}",
            stale.hook_commands
        );
    }
}

#[test]
fn generated_root_config_reproduces_the_reported_failure() {
    // The file chainlink #1145 reported, pinned by what it must contain: the
    // sandbox settings that made every socket fail with EPERM, the three hooks,
    // and the root-role MCP server whose PreToolUse guard denies edits.
    let rendered = generated_root_config("tl", "root");
    let parsed: toml::Value = toml::from_str(&rendered).expect("fixture parses as TOML");
    assert_eq!(parsed["approval_policy"].as_str(), Some("never"));
    assert_eq!(parsed["sandbox_mode"].as_str(), Some("workspace-write"));
    assert_eq!(
        parsed["sandbox_workspace_write"]["network_access"].as_bool(),
        Some(false)
    );
    assert_eq!(parsed["features"]["hooks"].as_bool(), Some(true));
    assert_eq!(
        parsed["mcp_servers"]["exomonad"]["args"]
            .as_array()
            .unwrap()
            .iter()
            .map(|arg| arg.as_str().unwrap())
            .collect::<Vec<_>>(),
        vec!["mcp-stdio", "--role", "tl", "--name", "root"]
    );
}

#[test]
fn a_generated_config_for_a_non_retired_role_is_reported_but_never_retired() {
    // Same generated config, but ExoMonad registered it for a non-root role, so
    // it is reported and left alone rather than refused over.
    let dir = project_with_generated_root("dev", "dev-agent");
    let stale = detect(dir.path())
        .unwrap()
        .expect("still ExoMonad-generated");
    assert_eq!(stale.role, "dev");

    enforce(dir.path(), false).unwrap();
    enforce(dir.path(), true).unwrap();
    assert!(dir.path().join(PROJECT_ROOT_CODEX_CONFIG).exists());
    assert!(!dir
        .path()
        .join(".codex/config.toml.exomonad-stale.1.bak")
        .exists());
}

#[test]
fn a_single_ownership_signal_is_not_enough() {
    let dir = tempfile::tempdir().unwrap();

    // Hooks but no exomonad MCP server: a hand-written project Codex config that
    // happens to call the ExoMonad hook binary is the operator's file.
    write_project_root_config(
        dir.path(),
        "[[hooks.Stop]]\n\n\
         [[hooks.Stop.hooks]]\n\
         type = \"command\"\n\
         command = \"/usr/local/bin/exomonad hook stop --runtime codex\"\n",
    );
    assert!(detect(dir.path()).unwrap().is_none());
    assert!(enforce(dir.path(), true).is_ok());
    assert!(dir.path().join(PROJECT_ROOT_CODEX_CONFIG).exists());

    // The exomonad MCP server but no ExoMonad Codex hook command: a project that
    // uses the ExoMonad MCP tools without ExoMonad having written this file.
    write_project_root_config(
        dir.path(),
        "[mcp_servers.exomonad]\n\
         command = \"exomonad\"\n\
         args = [\"mcp-stdio\", \"--role\", \"tl\", \"--name\", \"root\"]\n",
    );
    assert!(detect(dir.path()).unwrap().is_none());
    assert!(enforce(dir.path(), true).is_ok());
    assert!(dir.path().join(PROJECT_ROOT_CODEX_CONFIG).exists());
}

#[test]
fn a_foreign_project_root_config_is_never_touched() {
    let dir = tempfile::tempdir().unwrap();
    let operator_config = "model = \"gpt-5.2-codex\"\n\n\
                           [mcp_servers.docs]\n\
                           command = \"npx\"\n\
                           args = [\"-y\", \"@modelcontextprotocol/server-filesystem\"]\n";
    write_project_root_config(dir.path(), operator_config);

    assert!(detect(dir.path()).unwrap().is_none());
    for allow_retire in [false, true] {
        enforce(dir.path(), allow_retire).unwrap();
    }
    assert_eq!(
        std::fs::read_to_string(dir.path().join(PROJECT_ROOT_CODEX_CONFIG)).unwrap(),
        operator_config
    );
}

#[test]
fn unparsable_and_absent_project_root_configs_are_not_claimed() {
    let dir = tempfile::tempdir().unwrap();
    assert!(detect(dir.path()).unwrap().is_none());
    enforce(dir.path(), false).unwrap();

    write_project_root_config(dir.path(), "this is not = = valid toml\n");
    assert!(
        detect(dir.path()).unwrap().is_none(),
        "ExoMonad must only claim a config it can read back as one it wrote"
    );
    enforce(dir.path(), true).unwrap();
    assert!(dir.path().join(PROJECT_ROOT_CODEX_CONFIG).exists());
}

#[test]
fn instructions_quoting_a_hook_command_are_not_hook_evidence() {
    // The refusal must be driven by commands under `hooks`, never by prose. A
    // root-role MCP server plus instructions that mention `exomonad hook stop
    // --runtime codex` is not a config ExoMonad wrote.
    let dir = tempfile::tempdir().unwrap();
    write_project_root_config(
        dir.path(),
        "developer_instructions = \"\"\"\n\
         Run `/usr/local/bin/exomonad hook stop --runtime codex` when finished.\n\
         \"\"\"\n\n\
         [mcp_servers.exomonad]\n\
         command = \"exomonad\"\n\
         args = [\"mcp-stdio\", \"--role\", \"tl\", \"--name\", \"root\"]\n",
    );
    assert!(detect(dir.path()).unwrap().is_none());
    enforce(dir.path(), false).unwrap();
}

#[test]
fn only_the_project_root_is_inspected() {
    // Agent directories keep their generated configs forever; they are live state
    // the Codex trust lifecycle owns, not residue to retire.
    let dir = tempfile::tempdir().unwrap();
    let agent_config = dir
        .path()
        .join(".exo/agents/root")
        .join(PROJECT_ROOT_CODEX_CONFIG);
    std::fs::create_dir_all(agent_config.parent().unwrap()).unwrap();
    std::fs::write(&agent_config, generated_root_config("tl", "root")).unwrap();

    assert!(detect(dir.path()).unwrap().is_none());
    enforce(dir.path(), true).unwrap();
    assert!(agent_config.exists());
}

#[test]
fn enforce_fails_loudly_naming_the_file_and_the_repair() {
    let dir = project_with_generated_root("tl", "root");
    let error = enforce(dir.path(), false).expect_err("the stale root config must refuse");
    let message = refusal_from(error);

    assert!(message.contains(PROJECT_ROOT_CODEX_CONFIG), "{message}");
    assert!(
        message.contains(&format!(
            "mv {PROJECT_ROOT_CODEX_CONFIG} .codex/config.toml.exomonad-stale.1.bak"
        )),
        "{message}"
    );
    assert!(message.contains(RETIRE_FLAG), "{message}");
    assert!(message.contains("--role tl --name root"), "{message}");
    assert!(message.contains("codex-prune-trust"), "{message}");
    assert!(
        dir.path().join(PROJECT_ROOT_CODEX_CONFIG).exists(),
        "a refusal must not have touched the file"
    );
}

#[test]
fn the_flag_retires_the_config_and_leaves_a_readable_backup() {
    let dir = project_with_generated_root("tl", "root");
    let original = std::fs::read_to_string(dir.path().join(PROJECT_ROOT_CODEX_CONFIG)).unwrap();

    enforce(dir.path(), true).unwrap();

    assert!(!dir.path().join(PROJECT_ROOT_CODEX_CONFIG).exists());
    let backup = dir.path().join(".codex/config.toml.exomonad-stale.1.bak");
    assert_eq!(std::fs::read_to_string(&backup).unwrap(), original);
    // Retiring once must be enough; a second init sees nothing to do.
    assert!(detect(dir.path()).unwrap().is_none());
    enforce(dir.path(), false).unwrap();
}

#[test]
fn retirement_never_overwrites_an_existing_backup() {
    let dir = project_with_generated_root("tl", "root");
    let first = dir.path().join(".codex/config.toml.exomonad-stale.1.bak");
    std::fs::write(&first, "an earlier backup ExoMonad must preserve").unwrap();

    enforce(dir.path(), true).unwrap();

    assert_eq!(
        std::fs::read_to_string(&first).unwrap(),
        "an earlier backup ExoMonad must preserve"
    );
    assert!(dir
        .path()
        .join(".codex/config.toml.exomonad-stale.2.bak")
        .exists());
    assert!(!dir.path().join(PROJECT_ROOT_CODEX_CONFIG).exists());
}

#[test]
fn the_backup_search_reports_exhaustion_instead_of_overwriting() {
    let dir = project_with_generated_root("tl", "root");
    let config_path = dir.path().join(PROJECT_ROOT_CODEX_CONFIG);
    for attempt in 1..=MAX_BACKUP_ATTEMPTS {
        std::fs::write(
            dir.path()
                .join(".codex")
                .join(format!("config.toml{RETIRED_SUFFIX}.{attempt}.bak")),
            "taken\n",
        )
        .unwrap();
    }

    let error = unused_backup_path(&config_path).expect_err("no backup path is left");
    assert!(
        format!("{error:#}").contains("Cannot find an unused backup path"),
        "{error:#}"
    );
    // The refusal must surface the same exhaustion rather than name a path the
    // operator's `mv` would clobber.
    assert!(enforce(dir.path(), true).is_err());
    assert!(config_path.exists());
}

#[test]
fn the_refusal_names_the_first_unused_backup_path() {
    let dir = project_with_generated_root("tl", "root");
    std::fs::write(
        dir.path().join(".codex/config.toml.exomonad-stale.1.bak"),
        "already here\n",
    )
    .unwrap();

    let message = refusal_from(enforce(dir.path(), false).expect_err("must still refuse"));

    assert!(
        message.contains("mv .codex/config.toml .codex/config.toml.exomonad-stale.2.bak"),
        "{message}"
    );
}
