"""Ledger-backed controller event projections."""

from .bridge import BridgeError, EventBridge, bridge_event
from .envelope import (
    EVENT_TYPE_BY_KIND,
    KIND_BY_EVENT_TYPE,
    MAPPED_EVENT_TYPES,
    SERVER_EMIT_HEAD_SHA_GAPS,
    EnvelopeError,
    EventEnvelope,
    EventKind,
    InvalidLedgerEvent,
    UnmappedEventType,
    project,
    project_ledger_event,
)
from .queue import DEFAULT_ACTIVE_TAIL_TIMEOUT_SECONDS, EventQueue, LedgerQueue, QueueError
from .reader import (
    DEFAULT_LEDGER_ROOT,
    ActiveTail,
    FindingKind,
    LedgerFinding,
    LedgerReader,
    LedgerReadError,
    LedgerRow,
    ReadResult,
    SequenceStatus,
    sequence_status,
)
from .recovery import (
    AuthorizationSource,
    ParallelImpact,
    PolicyDecision,
    RecoveryDimensions,
    RecoveryOutcome,
    RecoveryTelemetryError,
)
from .stall import CiFailureAttribution, ReviewStallClassification, classify_review_stall

__all__ = [
    "DEFAULT_ACTIVE_TAIL_TIMEOUT_SECONDS",
    "DEFAULT_LEDGER_ROOT",
    "EVENT_TYPE_BY_KIND",
    "KIND_BY_EVENT_TYPE",
    "MAPPED_EVENT_TYPES",
    "SERVER_EMIT_HEAD_SHA_GAPS",
    "ActiveTail",
    "AuthorizationSource",
    "BridgeError",
    "CiFailureAttribution",
    "EnvelopeError",
    "EventBridge",
    "EventEnvelope",
    "EventKind",
    "EventQueue",
    "FindingKind",
    "InvalidLedgerEvent",
    "LedgerFinding",
    "LedgerQueue",
    "LedgerReadError",
    "LedgerReader",
    "LedgerRow",
    "ParallelImpact",
    "PolicyDecision",
    "QueueError",
    "ReadResult",
    "RecoveryDimensions",
    "RecoveryOutcome",
    "RecoveryTelemetryError",
    "ReviewStallClassification",
    "SequenceStatus",
    "UnmappedEventType",
    "bridge_event",
    "classify_review_stall",
    "project",
    "project_ledger_event",
    "sequence_status",
]
