"""Recursive-language-model integration boundary."""

from .budget import (
    SECTION_PRIORITY_ORDER,
    ApproximateTokenCounter,
    CompactionResult,
    ContextBudgetError,
    ContextOverflow,
    InputSection,
    compact_inputs,
    compact_sections,
    context_budget,
    resolve_token_counter,
    sections_from_inputs,
)
from .call import (
    MAX_ATTEMPTS,
    JudgmentFailed,
    RlmCallError,
    RlmConfigurationError,
    RlmError,
    judgment_hash,
    rlm,
)
from .decompose import (
    DECOMPOSE_PROMPT,
    SLICE_SPEC_SCHEMA,
    DecompositionConfigurationError,
    DecompositionParked,
    DecompositionValidationError,
    SliceSpec,
    decompose,
    validate_decomposition,
)
from .schema import OutputSchemaError, validate_output
from .store import (
    BudgetExceeded,
    RlmBackend,
    RlmCallStore,
    RlmModelChoice,
    RlmRequest,
    RlmResponse,
    RlmRoleLedger,
)

__all__ = [
    "DECOMPOSE_PROMPT",
    "MAX_ATTEMPTS",
    "SECTION_PRIORITY_ORDER",
    "SLICE_SPEC_SCHEMA",
    "ApproximateTokenCounter",
    "BudgetExceeded",
    "CompactionResult",
    "ContextBudgetError",
    "ContextOverflow",
    "DecompositionConfigurationError",
    "DecompositionParked",
    "DecompositionValidationError",
    "InputSection",
    "JudgmentFailed",
    "OutputSchemaError",
    "RlmBackend",
    "RlmCallError",
    "RlmCallStore",
    "RlmConfigurationError",
    "RlmError",
    "RlmModelChoice",
    "RlmRequest",
    "RlmResponse",
    "RlmRoleLedger",
    "SliceSpec",
    "compact_inputs",
    "compact_sections",
    "context_budget",
    "decompose",
    "judgment_hash",
    "resolve_token_counter",
    "rlm",
    "sections_from_inputs",
    "validate_decomposition",
    "validate_output",
]
